// Get/Create data list container
// var site = companyhome.childByNamePath("Sites/swsdp");
// var dataListContainer = "dataLists";
// var dataLists = site.getContainer(dataListContainer);
// var site = siteService.getSite("swsdp");
var site = siteService.getSite("vendor-list");
var dataLists = site.getContainer("dataLists");

var vendorListName = "Vendor List";
var vendorList = dataLists.childByNamePath(vendorListName);

var vendorListItemType = "acmedl:VendorListItem";

// Add an item to the vendor list
var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ventilation Fan";
item.properties["acmedl:VL_Company"] = "Shanghai Blower Works Co.,Ltd. 上海鼓风机厂有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lv Chunjin";
item.properties["acmedl:VL_Telephone"] = "021-56650577-398";
item.properties["acmedl:VL_MobilePhone"] = "13701992528";
item.properties["acmedl:VL_Email"] = "sales@sbw-cn.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ventilation Fan";
item.properties["acmedl:VL_Company"] = "HALIFAX 哈利法克斯风机（深圳）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Kevin Liang";
item.properties["acmedl:VL_Telephone"] = "0755-81490059-823";
item.properties["acmedl:VL_MobilePhone"] = "136-3255-2079";
item.properties["acmedl:VL_Email"] = "mailto:KevinLiang@halifax-fan.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ventilation Fan";
item.properties["acmedl:VL_Company"] = "Zhejiang Zhefeng group 浙江浙风集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr.Liang/ Ms.Xu";
item.properties["acmedl:VL_Telephone"] = "0575 82366508";
item.properties["acmedl:VL_MobilePhone"] = "13906850987/15258509430";
item.properties["acmedl:VL_Email"] = "mailto:zhefeng@zhefeng.net";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ventilation Fan";
item.properties["acmedl:VL_Company"] = "GREENHECK 格林瀚克通风设备（昆山）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu Naizheng/ Zhang Jun(Ag)";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13761355913/15900782223";
item.properties["acmedl:VL_Email"] = "mailto:naizheng.yu@greenheck.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Joton Special Equipment(Shanghai)Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr.Xiang";
item.properties["acmedl:VL_Telephone"] = "021 22818949";
item.properties["acmedl:VL_MobilePhone"] = "13901818979";
item.properties["acmedl:VL_Email"] = "mailto:king2001911@vip.sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Emerson Network Power";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Yi";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "18606204321";
item.properties["acmedl:VL_Email"] = "mailto:18606204321@qq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Hiross-Shanghai Chat Union Development Ltd.,";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Zhe";
item.properties["acmedl:VL_Telephone"] = "021-64180979";
item.properties["acmedl:VL_MobilePhone"] = "13331877525";
item.properties["acmedl:VL_Email"] = "mailto:sunerji@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Stulz Air Technology & Services Shanghai Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Kathy tong";
item.properties["acmedl:VL_Telephone"] = "021-33607133-7103";
item.properties["acmedl:VL_MobilePhone"] = "13901927739";
item.properties["acmedl:VL_Email"] = "mailto:kathy.tong@stulz.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Wuxi Harubishi Engineering Co., Ltd. (Trane) 无锡春菱机电设备工程有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Hongbing";
item.properties["acmedl:VL_Telephone"] = "0510-82409465";
item.properties["acmedl:VL_MobilePhone"] = "13906186108";
item.properties["acmedl:VL_Email"] = "491159319@qq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Maquay";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhu Dawei";
item.properties["acmedl:VL_Telephone"] = "010-65884838/";
item.properties["acmedl:VL_MobilePhone"] = "13501222395/18600063708";
item.properties["acmedl:VL_Email"] = "yvw315@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Guangdong Jirong Air-conditioning Co., Ltd. 广东省吉荣空调设备公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wu Yisan";
item.properties["acmedl:VL_Telephone"] = "010-5881 5339-246";
item.properties["acmedl:VL_MobilePhone"] = "13601170276";
item.properties["acmedl:VL_Email"] = "wys899@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Constant temprature and Humidity Air Conditioner";
item.properties["acmedl:VL_Company"] = "Beijing Shunde ShenLing Air Conditioning sales Co., Ltd.  北京顺德申菱空调销售有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Hu Yingchun";
item.properties["acmedl:VL_Telephone"] = "010-84094117";
item.properties["acmedl:VL_MobilePhone"] = "13552526662";
item.properties["acmedl:VL_Email"] = "zz760808@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety valve";
item.properties["acmedl:VL_Company"] = "LESER GmbH & Co. KG / via distributor: Hongkong Leser Safety controls limited 香港LESER安全控制有限公司 (for Leser )";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Wei";
item.properties["acmedl:VL_Telephone"] = "010-84885215";
item.properties["acmedl:VL_MobilePhone"] = "18910159257";
item.properties["acmedl:VL_Email"] = "protego_beijing@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety valve";
item.properties["acmedl:VL_Company"] = "Dresser";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Luo min";
item.properties["acmedl:VL_Telephone"] = "021-50312770";
item.properties["acmedl:VL_MobilePhone"] = "13816506356";
item.properties["acmedl:VL_Email"] = "chuanyi.yx@gmail.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety valve";
item.properties["acmedl:VL_Company"] = "Tyco Flow Control (Beijing) Co,.Ltd. 泰科流体控制（北京）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yan Min";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15900955892";
item.properties["acmedl:VL_Email"] = "ranyan@tyco-valves.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety valve";
item.properties["acmedl:VL_Company"] = "Safety Systems UK Ltd. Beijing Rep. Office 英国安全系统有限公司北京代表处";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Xuejun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13910030499";
item.properties["acmedl:VL_Email"] = "xili@safetysystemsuk.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Bag emptying hood";
item.properties["acmedl:VL_Company"] = "Shanghai Jiteng Electric Engineering Co.,Ltd.  上海骥腾机电工程有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhangpeng";
item.properties["acmedl:VL_Telephone"] = "021-58541848";
item.properties["acmedl:VL_MobilePhone"] = "13564365178";
item.properties["acmedl:VL_Email"] = "shjiteng@yahoo.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Bag emptying hood";
item.properties["acmedl:VL_Company"] = "Zhangjiagang Toway Equipment Co.,Ltd.  张家港拓维装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Roger Lee";
item.properties["acmedl:VL_Telephone"] = "0512-58356870";
item.properties["acmedl:VL_MobilePhone"] = "15895590598";
item.properties["acmedl:VL_Email"] = "lh@towayen-e.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Waste box";
item.properties["acmedl:VL_Company"] = "Shanghai Jiteng Electric Engineering Co.,Ltd.  上海骥腾机电工程有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhangpeng";
item.properties["acmedl:VL_Telephone"] = "021-58541848";
item.properties["acmedl:VL_MobilePhone"] = "13564365178";
item.properties["acmedl:VL_Email"] = "shjiteng@yahoo.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Waste box";
item.properties["acmedl:VL_Company"] = "Zhangjiagang Toway Equipment Co.,Ltd.  张家港拓维装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Roger Lee";
item.properties["acmedl:VL_Telephone"] = "0512-58356870";
item.properties["acmedl:VL_MobilePhone"] = "15895590598";
item.properties["acmedl:VL_Email"] = "lh@towayen-e.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "STAHL CraneSystems (Shanghai) Co., Ltd. 斯泰尔起重设备贸易（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shao Wensheng";
item.properties["acmedl:VL_Telephone"] = "021-66083737";
item.properties["acmedl:VL_MobilePhone"] = "13585627249";
item.properties["acmedl:VL_Email"] = "victor.shao@stahlcranes.com shaowensheng@live.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Verlinde Lifting Equipment 上海法兰特起重机械设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Steven Gu";
item.properties["acmedl:VL_Telephone"] = "021-5889 5533";
item.properties["acmedl:VL_MobilePhone"] = "13818808723";
item.properties["acmedl:VL_Email"] = "stevengu@eurocrane.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Nanjing Hoisting Machinery General Works 南京起重机械总厂有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wu Xiaojian";
item.properties["acmedl:VL_Telephone"] = "025-85503985";
item.properties["acmedl:VL_MobilePhone"] = "13605189401";
item.properties["acmedl:VL_Email"] = "wuxiao9111@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hand Lifting Trunk with Scale";
item.properties["acmedl:VL_Company"] = "CAS 上海凯士电子有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zuo Yichun";
item.properties["acmedl:VL_Telephone"] = "010-58612008";
item.properties["acmedl:VL_MobilePhone"] = "15801117190";
item.properties["acmedl:VL_Email"] = "mailto:zccstudio@yahoo.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hand Lifting Trunk with Scale";
item.properties["acmedl:VL_Company"] = "Bizerba 碧彩（上海）衡器技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhu Yiming";
item.properties["acmedl:VL_Telephone"] = "021-67600999-6106";
item.properties["acmedl:VL_MobilePhone"] = "15821382516";
item.properties["acmedl:VL_Email"] = "zhu.yiming@bizerba.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hand Lifting Trunk with Scale";
item.properties["acmedl:VL_Company"] = "Mettler-Toledo Changzhou Scale & System Ltd. 梅特勒-托利多（常州）称重设备系统有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yang Yang Xuan Hao";
item.properties["acmedl:VL_Telephone"] = "010-58523688-546 010-58523688-2256";
item.properties["acmedl:VL_MobilePhone"] = "13910756952 13910821230";
item.properties["acmedl:VL_Email"] = "mailto:yang.yang@mt.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Scale";
item.properties["acmedl:VL_Company"] = "Schenck Process (Tianjin) Industrial Technology Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "石沛欣";
item.properties["acmedl:VL_Telephone"] = "010-6481 8854";
item.properties["acmedl:VL_MobilePhone"] = "13801066021";
item.properties["acmedl:VL_Email"] = "mailto:shi.peixin@schenckprocess.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Scale";
item.properties["acmedl:VL_Company"] = "Bizerba 碧彩（上海）衡器技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhu Yiming";
item.properties["acmedl:VL_Telephone"] = "021-67600999-6106";
item.properties["acmedl:VL_MobilePhone"] = "15821382516";
item.properties["acmedl:VL_Email"] = "zhu.yiming@bizerba.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Scale";
item.properties["acmedl:VL_Company"] = "Sartorius 北京赛多利斯仪器系统有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Hou Ping Zhang Huacheng";
item.properties["acmedl:VL_Telephone"] = "010-80426532 010-51810290";
item.properties["acmedl:VL_MobilePhone"] = "13601386365 13810122188";
item.properties["acmedl:VL_Email"] = "mailto:ping.houbjzhc@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " Filter Cartridge ";
item.properties["acmedl:VL_Company"] = "EATON Filtration (Shanghai) Co., Ltd.  伊顿工业过滤（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lai Xiaowei";
item.properties["acmedl:VL_Telephone"] = "010-84580088-1002399";
item.properties["acmedl:VL_MobilePhone"] = "13911817976";
item.properties["acmedl:VL_Email"] = "masonlai@eaton.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " Filter Cartridge ";
item.properties["acmedl:VL_Company"] = "Pall filter Co., Ltd. 颇尔过滤器（北京）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Yin";
item.properties["acmedl:VL_Telephone"] = "010-84584010";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " Filter Cartridge ";
item.properties["acmedl:VL_Company"] = "Parker Zender / PARKER HANNIFIN MOTION & CONNTROL";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " Filter Cartridge ";
item.properties["acmedl:VL_Company"] = "Donaldson (Wuxi) Filters Co., Ltd.  唐纳森（无锡）过滤器有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mary Liu";
item.properties["acmedl:VL_Telephone"] = "010-83915225";
item.properties["acmedl:VL_MobilePhone"] = "13910109751";
item.properties["acmedl:VL_Email"] = "Mary.Liu@Donaldson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter Bag ";
item.properties["acmedl:VL_Company"] = "FSI(Filter Specialists (Shanghai) Co.,Ltd.) 丰泰过滤系统（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Jing Jun";
item.properties["acmedl:VL_Telephone"] = "021-59900950";
item.properties["acmedl:VL_MobilePhone"] = "13511035330";
item.properties["acmedl:VL_Email"] = "jjing@fsifilter.com jingjun626@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter Bag ";
item.properties["acmedl:VL_Company"] = "Feature (WuXi) Filtration Technology Co.,Ltd. 飞潮（无锡）过滤技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Sun Zhi Peng";
item.properties["acmedl:VL_Telephone"] = "010-51668396";
item.properties["acmedl:VL_MobilePhone"] = "15001380665";
item.properties["acmedl:VL_Email"] = "szp@feature-tec.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter Bag";
item.properties["acmedl:VL_Company"] = "Herding/Beijing Clean Air Technology Innovation Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Jianwen";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901386775";
item.properties["acmedl:VL_Email"] = "mailto:catico@vip.sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter Bag";
item.properties["acmedl:VL_Company"] = "AAF (Wuhan) Co. Ltd. AAF（武汉）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Nie XiaoLong";
item.properties["acmedl:VL_Telephone"] = "027-84236635";
item.properties["acmedl:VL_MobilePhone"] = "13307186086";
item.properties["acmedl:VL_Email"] = "xl.nie@aafwuhan.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Conveyer System";
item.properties["acmedl:VL_Company"] = "MSK Covertech (Qingdao) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Huang Rong";
item.properties["acmedl:VL_Telephone"] = "0532-85797620";
item.properties["acmedl:VL_MobilePhone"] = "18657177888";
item.properties["acmedl:VL_Email"] = "mailto:andy.huang@msk-covertech.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Conveyer System";
item.properties["acmedl:VL_Company"] = "Loedige Systems ( Beijing ) Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Gao Yihua";
item.properties["acmedl:VL_Telephone"] = "01084456080 0852-22373910";
item.properties["acmedl:VL_MobilePhone"] = "0852-94686010 13802887181";
item.properties["acmedl:VL_Email"] = "K.Ko@lodige.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Conveyer System";
item.properties["acmedl:VL_Company"] = "Shenzhen Tianhe-Shuangli Logistics Automation Equipment Co., Ltd.深圳天和双利机械有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yue Ping Dai Wei";
item.properties["acmedl:VL_Telephone"] = "021-54085406 0755-22652896";
item.properties["acmedl:VL_MobilePhone"] = "13636435520 13510088380";
item.properties["acmedl:VL_Email"] = "mailto:twsl@twsl.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Conveyer System";
item.properties["acmedl:VL_Company"] = "Haerbin Boshi Automatic Equipment Co.,Ltd. 哈尔滨博实自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Cui Zhiqiang";
item.properties["acmedl:VL_Telephone"] = "021-54933822";
item.properties["acmedl:VL_MobilePhone"] = "13796653242";
item.properties["acmedl:VL_Email"] = "mailto:13796653242@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Conveyer System";
item.properties["acmedl:VL_Company"] = "Changshu City Sanhe Measurement Equipment Factory 常熟市三禾计量设备厂";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Cheng Chong";
item.properties["acmedl:VL_Telephone"] = "0512-52594071-8013";
item.properties["acmedl:VL_MobilePhone"] = "13913682134";
item.properties["acmedl:VL_Email"] = "mailto:cc@san-he.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Warm Water Supply System";
item.properties["acmedl:VL_Company"] = "Spirax Sarco China 斯派莎克工程（中国）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Guangqiang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13810898270";
item.properties["acmedl:VL_Email"] = "mailto:lee.li@cn.spiraxsarco.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Warm Water Supply System";
item.properties["acmedl:VL_Company"] = "Lauda";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Michael Lin  吝俊友";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "021 6440 1098";
item.properties["acmedl:VL_Email"] = "mailto:michael.lin@lauda.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Warm Water Supply System";
item.properties["acmedl:VL_Company"] = "APV";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wang wei";
item.properties["acmedl:VL_Telephone"] = "13917012973";
item.properties["acmedl:VL_MobilePhone"] = "021-22085759";
item.properties["acmedl:VL_Email"] = "mailto:wei.w.wang@spx.com；wanyewang@yahoo.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Warm Water Supply System";
item.properties["acmedl:VL_Company"] = "Hot Water 哈瓦特换热机组（北京）有限公司上海分公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Qiang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13916345810";
item.properties["acmedl:VL_Email"] = "dennis.li@hwdhs.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Warm Water Supply System";
item.properties["acmedl:VL_Company"] = "SmartHeat Taiyu (Shenyang)Energy Technology Co., Ltd.-Sentry 睿能太宇(沈阳)能源技术有限公司-Sentry";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Susan Su";
item.properties["acmedl:VL_Telephone"] = "024-2519 7622";
item.properties["acmedl:VL_MobilePhone"] = "13332432657";
item.properties["acmedl:VL_Email"] = "Susan.su@smartheatgroup.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Submerge Pump";
item.properties["acmedl:VL_Company"] = "Shanghai Liancheng (Group) CO., Ltd. 上海连成集团公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Guilin Liu Guoyin";
item.properties["acmedl:VL_Telephone"] = "010-65031586";
item.properties["acmedl:VL_MobilePhone"] = "13810199313 13146968594";
item.properties["acmedl:VL_Email"] = "mailto:bjliugy@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Submerge Pump";
item.properties["acmedl:VL_Company"] = "Xlem (ITT)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Daisy Li Ma Yanjun";
item.properties["acmedl:VL_Telephone"] = "021 -22082888-8819";
item.properties["acmedl:VL_MobilePhone"] = "13916897654 18621691062";
item.properties["acmedl:VL_Email"] = "mailto:joe.ma@itt.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Submerge Pump";
item.properties["acmedl:VL_Company"] = "KSB Shanghai Pump Co. Ltd. 上海凯士比泵有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Kui Li Menglu";
item.properties["acmedl:VL_Telephone"] = "021-64857597 021-64302888-1766";
item.properties["acmedl:VL_MobilePhone"] = "18621581599 18616800109";
item.properties["acmedl:VL_Email"] = "Kui.Li@ksb.com Menglu.Li@ksb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Submerge Pump";
item.properties["acmedl:VL_Company"] = "Nanjing Lanshen Group Pump Co., Ltd. 南京蓝深制泵集团股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Xie Feng";
item.properties["acmedl:VL_Telephone"] = "021-59573365/64383006";
item.properties["acmedl:VL_MobilePhone"] = "13524156930";
item.properties["acmedl:VL_Email"] = "mailto:xiefjin@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "ROTAN gear Pump ROTAN齿轮泵公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Richard Jiang Jin He Chen Zhi";
item.properties["acmedl:VL_Telephone"] = "0512-62740400 022-23235087";
item.properties["acmedl:VL_MobilePhone"] = "13506132693 13802092364";
item.properties["acmedl:VL_Email"] = "rji@desmi.com dhe@desmi.com cz@pump-kin.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "KRACHT 有限责任公司上海代表处";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yuan Jianhong             Oliver Passolat";
item.properties["acmedl:VL_Telephone"] = "021-50892960 021-50892960";
item.properties["acmedl:VL_MobilePhone"] = "18721260745 13795486799";
item.properties["acmedl:VL_Email"] = "mailto:david.yuan@kracht.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "Maag Pump (high pressure) 马格泵";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yao Qi Ren Zhanguo";
item.properties["acmedl:VL_Telephone"] = "010-61272451";
item.properties["acmedl:VL_MobilePhone"] = "13917273639 13910550936";
item.properties["acmedl:VL_Email"] = "rogeryao@maag.com bjaute@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "Viking Pump Inc.  威肯泵";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Jiang XianQuan Li Xiaoning";
item.properties["acmedl:VL_Telephone"] = "021-52415599 010-67115682";
item.properties["acmedl:VL_MobilePhone"] = "13816809710 13910983412";
item.properties["acmedl:VL_Email"] = "sjiang@idexcorp.com ezhang@idexcorp.com terry@grandeco.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "VARISCO S.p.A  流金泵业(天津)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Ming";
item.properties["acmedl:VL_Telephone"] = "022-86880500";
item.properties["acmedl:VL_MobilePhone"] = "18622661679";
item.properties["acmedl:VL_Email"] = "mailto:mingliu_616@yahoo.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gear Pump齿轮泵";
item.properties["acmedl:VL_Company"] = "Dalian Hermetic Pump Co., Ltd. 大连海密梯克泵业有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Huacheng";
item.properties["acmedl:VL_Telephone"] = "010-82860227";
item.properties["acmedl:VL_MobilePhone"] = "13998452666";
item.properties["acmedl:VL_Email"] = "mailto:liuhuacheng@hermetic.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Diaphragm Pump隔膜泵";
item.properties["acmedl:VL_Company"] = "Verder Pump 弗尔德工业集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Long Gaofeng";
item.properties["acmedl:VL_Telephone"] = "021-57635898-119";
item.properties["acmedl:VL_MobilePhone"] = "13816727021";
item.properties["acmedl:VL_Email"] = "raymond@china-chengfeng.net";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Diaphragm Pump隔膜泵";
item.properties["acmedl:VL_Company"] = "Ingersoll Rand Pump (ARO) 英格索兰泵业";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Yinghua He Ying Wang Weihua";
item.properties["acmedl:VL_Telephone"] = "021-51996563";
item.properties["acmedl:VL_MobilePhone"] = "13917616256 13818156199 13917021000";
item.properties["acmedl:VL_Email"] = "mailto:cz@pump-kin.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Diaphragm Pump隔膜泵";
item.properties["acmedl:VL_Company"] = "Wilden Pump & Engineering, LLC   威尔顿泵业";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Cui Chunqiang";
item.properties["acmedl:VL_Telephone"] = "010-87286152-101";
item.properties["acmedl:VL_MobilePhone"] = "13683211414";
item.properties["acmedl:VL_Email"] = "ccq777777666666@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Diaphragm Pump隔膜泵";
item.properties["acmedl:VL_Company"] = "IDEX, AODD (Warren Rupp) 艺达思贸易（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Louis Lu";
item.properties["acmedl:VL_Telephone"] = "021-52415599-119";
item.properties["acmedl:VL_MobilePhone"] = "13818026580";
item.properties["acmedl:VL_Email"] = "llu@idexcorp.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Hamilton-Sundstrand Industrial (Shanghai) Co., Ltd.  汉胜工业设备（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "Hamilton-Sundstrand";
item.properties["acmedl:VL_Contact"] = "li qinghe";
item.properties["acmedl:VL_Telephone"] = "010-59070641";
item.properties["acmedl:VL_MobilePhone"] = "13511006910";
item.properties["acmedl:VL_Email"] = "mailto:louie.chen@hs.utc.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "KSB Shanghai Pump Co. Ltd. 上海凯士比泵有限公司";
item.properties["acmedl:VL_Brand"] = "KSB";
item.properties["acmedl:VL_Contact"] = "Li Kui Li Menglu Bian Yong";
item.properties["acmedl:VL_Telephone"] = "021-64857597 021-64302888-1766 021-64302888-1711";
item.properties["acmedl:VL_MobilePhone"] = "18621581599 18616800109";
item.properties["acmedl:VL_Email"] = "Kui.Li@ksb.com Menglu.Li@ksb.com yong.bian@ksb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "KLAUS UNION  宁波克劳斯机械有限公司";
item.properties["acmedl:VL_Brand"] = "KLAUS";
item.properties["acmedl:VL_Contact"] = "Daisy Dai";
item.properties["acmedl:VL_Telephone"] = "0574-88167810";
item.properties["acmedl:VL_MobilePhone"] = "18957828290";
item.properties["acmedl:VL_Email"] = "daisy@klausunion.cn terry@grandeco.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Dalian Hermetic Pump Co., Ltd. 大连海密梯克泵业有限公司";
item.properties["acmedl:VL_Brand"] = "Hermetic";
item.properties["acmedl:VL_Contact"] = "Liu Huacheng";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13998452666";
item.properties["acmedl:VL_Email"] = "mailto:liuhuacheng@hermetic.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Mobile Container";
item.properties["acmedl:VL_Company"] = "UCON, Hausach, Germany:www.ucon.de";
item.properties["acmedl:VL_Brand"] = "UCON";
item.properties["acmedl:VL_Contact"] = "Werner Fuchs";
item.properties["acmedl:VL_Telephone"] = "49 783177280";
item.properties["acmedl:VL_MobilePhone"] = "0172 760 5556";
item.properties["acmedl:VL_Email"] = "mailto:werner.fuchs@ucon.de";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Coaxial pipe heat exchanger";
item.properties["acmedl:VL_Company"] = "Zhangjiagang Toway Equipment Co.,Ltd.  张家港拓维装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Roger Lee";
item.properties["acmedl:VL_Telephone"] = "0512-58356870";
item.properties["acmedl:VL_MobilePhone"] = "15895590598";
item.properties["acmedl:VL_Email"] = "mailto:lh@towayen-e.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Coaxial pipe heat exchanger";
item.properties["acmedl:VL_Company"] = "SmartHeat (Sentry )睿能集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Susan Su";
item.properties["acmedl:VL_Telephone"] = "024-2519 7622";
item.properties["acmedl:VL_MobilePhone"] = "13332432657";
item.properties["acmedl:VL_Email"] = "Susan.su@smartheatgroup.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Coaxial pipe heat exchanger";
item.properties["acmedl:VL_Company"] = "BEHNCKE GMBH";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Csilla NEMES";
item.properties["acmedl:VL_Telephone"] = "49(0)89456917-22";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "info@behncke.com/csilla_nemes@behncke.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Piping";
item.properties["acmedl:VL_Company"] = "Buhlmann Steel Pipe Trading (Shanghai) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "Benteler";
item.properties["acmedl:VL_Contact"] = "Kurt WANG";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "139 1683 3371";
item.properties["acmedl:VL_Email"] = "mailto:kurt.wang@buhlmann-group.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Manual Valve";
item.properties["acmedl:VL_Company"] = "Bray (China) Controls Co. Ltd.";
item.properties["acmedl:VL_Brand"] = "Bray";
item.properties["acmedl:VL_Contact"] = "ci jing";
item.properties["acmedl:VL_Telephone"] = "010-65669231";
item.properties["acmedl:VL_MobilePhone"] = "135 0110 2550";
item.properties["acmedl:VL_Email"] = "mailto:jing.ci@bray.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Manual Valve";
item.properties["acmedl:VL_Company"] = "Flowserve US Inc.";
item.properties["acmedl:VL_Brand"] = "FLOWSERVE";
item.properties["acmedl:VL_Contact"] = "Benjamin Jing";
item.properties["acmedl:VL_Telephone"] = "86 21 38654819";
item.properties["acmedl:VL_MobilePhone"] = "139 1743 1736";
item.properties["acmedl:VL_Email"] = "mailto:BJing@flowserve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Manual Valve";
item.properties["acmedl:VL_Company"] = "Beijing Century Longtime International Limited";
item.properties["acmedl:VL_Brand"] = "Valvitalia";
item.properties["acmedl:VL_Contact"] = "pan xuan";
item.properties["acmedl:VL_Telephone"] = "+86 10 6556 5059";
item.properties["acmedl:VL_MobilePhone"] = "152 1016 9146";
item.properties["acmedl:VL_Email"] = "shijilangteng@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Manual Valve";
item.properties["acmedl:VL_Company"] = "TALOAR INC.Beijing Office";
item.properties["acmedl:VL_Brand"] = "TALOAR";
item.properties["acmedl:VL_Contact"] = "Mavis li";
item.properties["acmedl:VL_Telephone"] = "86-10-65001586";
item.properties["acmedl:VL_MobilePhone"] = "136 4139 8013";
item.properties["acmedl:VL_Email"] = "mailto:mavisli@taloar.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Manual Valve";
item.properties["acmedl:VL_Company"] = "Shanghai Neles-Jamesbury Valve Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "Neles";
item.properties["acmedl:VL_Contact"] = "Jethro Zhu";
item.properties["acmedl:VL_Telephone"] = "tel:+86";
item.properties["acmedl:VL_MobilePhone"] = "139 1788 8256";
item.properties["acmedl:VL_Email"] = "mailto:zhury@snjvalve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Moisture Analyzer";
item.properties["acmedl:VL_Company"] = "Michell Instruments shanghai co.,ltd";
item.properties["acmedl:VL_Brand"] = "Michell";
item.properties["acmedl:VL_Contact"] = "zhang libin";
item.properties["acmedl:VL_Telephone"] = "010-68650925-802";
item.properties["acmedl:VL_MobilePhone"] = "138 1090 1406";
item.properties["acmedl:VL_Email"] = "jonathan.zhang@michell.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Moisture Analyzer";
item.properties["acmedl:VL_Company"] = "Beijing Kallon Analyzer instruments co.,ltd";
item.properties["acmedl:VL_Brand"] = "Xentaur";
item.properties["acmedl:VL_Contact"] = "Chen yue";
item.properties["acmedl:VL_Telephone"] = "010-65900635";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "kaloon@vip.163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Software and Hardware for Numerical Control";
item.properties["acmedl:VL_Company"] = "Beijing Willtech Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "AB";
item.properties["acmedl:VL_Contact"] = "Sun yutao";
item.properties["acmedl:VL_Telephone"] = "010-62976969-637";
item.properties["acmedl:VL_MobilePhone"] = "138 1068 3545";
item.properties["acmedl:VL_Email"] = "mailto:sunyt@will-tech.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Software and Hardware for Numerical Control";
item.properties["acmedl:VL_Company"] = "ROSEMOUNT";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-58211000";
item.properties["acmedl:VL_MobilePhone"] = "150 0113 5685";
item.properties["acmedl:VL_Email"] = "mailto:Mingxuan.Xu@Emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Software and Hardware for Numerical Control";
item.properties["acmedl:VL_Company"] = "SIEMENS China";
item.properties["acmedl:VL_Brand"] = "SIEMENS";
item.properties["acmedl:VL_Contact"] = "Dong quanyu";
item.properties["acmedl:VL_Telephone"] = "010-64768888";
item.properties["acmedl:VL_MobilePhone"] = "138 1145 1668";
item.properties["acmedl:VL_Email"] = "mailto:quanyu.dong@siements.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Control Valve";
item.properties["acmedl:VL_Company"] = "Flowserve US Inc.";
item.properties["acmedl:VL_Brand"] = "FLOWSERVE";
item.properties["acmedl:VL_Contact"] = "Eric Zhou";
item.properties["acmedl:VL_Telephone"] = "0512-62881897";
item.properties["acmedl:VL_MobilePhone"] = "138 6256 9058";
item.properties["acmedl:VL_Email"] = "mailto:ezhou@flowserve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Control Valve";
item.properties["acmedl:VL_Company"] = "Hanoyer Valve Group.";
item.properties["acmedl:VL_Brand"] = "Hanoyer";
item.properties["acmedl:VL_Contact"] = "Wang Rui";
item.properties["acmedl:VL_Telephone"] = "010-63785776";
item.properties["acmedl:VL_MobilePhone"] = "138 1126 1158";
item.properties["acmedl:VL_Email"] = "mailto:w13811261158@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Control Valve";
item.properties["acmedl:VL_Company"] = "SAMSON Controls (China) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "Samson";
item.properties["acmedl:VL_Contact"] = "Anita Lin";
item.properties["acmedl:VL_Telephone"] = "+86 10 6780 3011-205";
item.properties["acmedl:VL_MobilePhone"] = "139 11594091";
item.properties["acmedl:VL_Email"] = "mailto:anita@samsonchina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pneumatic On-Off Valve";
item.properties["acmedl:VL_Company"] = "Flowserve";
item.properties["acmedl:VL_Brand"] = "FLOWSERVE";
item.properties["acmedl:VL_Contact"] = "Benjamin Jing";
item.properties["acmedl:VL_Telephone"] = "86 21 38654819";
item.properties["acmedl:VL_MobilePhone"] = "139 1743 1736";
item.properties["acmedl:VL_Email"] = "mailto:BJing@flowserve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pneumatic On-Off Valve";
item.properties["acmedl:VL_Company"] = "KITZ CORPORATION OF SHANGHAI";
item.properties["acmedl:VL_Brand"] = "KITZ";
item.properties["acmedl:VL_Contact"] = "liu zhixin";
item.properties["acmedl:VL_Telephone"] = "022-26986036";
item.properties["acmedl:VL_MobilePhone"] = "137 5201 9802";
item.properties["acmedl:VL_Email"] = "mailto:george.liu@globedragon.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pneumatic On-Off Valve";
item.properties["acmedl:VL_Company"] = "Bray (China) Controls Co. Ltd.";
item.properties["acmedl:VL_Brand"] = "Bray";
item.properties["acmedl:VL_Contact"] = "ci jing";
item.properties["acmedl:VL_Telephone"] = "010-65669231";
item.properties["acmedl:VL_MobilePhone"] = "135 0110 2550";
item.properties["acmedl:VL_Email"] = "mailto:jing.ci@bray.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Votux Flow Meter";
item.properties["acmedl:VL_Company"] = "Beijing Century Longtime International Limited";
item.properties["acmedl:VL_Brand"] = "E+H";
item.properties["acmedl:VL_Contact"] = "pan xuan";
item.properties["acmedl:VL_Telephone"] = "+86 10 6556 5059";
item.properties["acmedl:VL_MobilePhone"] = "152 1016 9146";
item.properties["acmedl:VL_Email"] = "shijilangteng@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Controller and Dump Valve";
item.properties["acmedl:VL_Company"] = "Beijing Taihexingyuan Technology(Beijing co.,ltd)";
item.properties["acmedl:VL_Brand"] = "Kenco";
item.properties["acmedl:VL_Contact"] = "xing hongtao";
item.properties["acmedl:VL_Telephone"] = "010-64440649";
item.properties["acmedl:VL_MobilePhone"] = "136 2111 4229";
item.properties["acmedl:VL_Email"] = "mailto:taihexy@vip.sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Controller and Dump Valve";
item.properties["acmedl:VL_Company"] = "CNMEC Technology(Beijing co.,ltd)";
item.properties["acmedl:VL_Brand"] = "Murphy";
item.properties["acmedl:VL_Contact"] = "yang sir";
item.properties["acmedl:VL_Telephone"] = "010-8428 8762";
item.properties["acmedl:VL_MobilePhone"] = "139 1096 2635";
item.properties["acmedl:VL_Email"] = "mailto:sales@cnmec.biz";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Controller and Dump Valve";
item.properties["acmedl:VL_Company"] = "Noriseal USA";
item.properties["acmedl:VL_Brand"] = "Noriseal";
item.properties["acmedl:VL_Contact"] = "Thomas";
item.properties["acmedl:VL_Telephone"] = "(713) 466-3552";
item.properties["acmedl:VL_MobilePhone"] = "7138491231";
item.properties["acmedl:VL_Email"] = "mailto:tmendenhall@norriseal.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Switch";
item.properties["acmedl:VL_Company"] = "Shanghai KSR-KUEBLER Automation Instrument Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "KSR";
item.properties["acmedl:VL_Contact"] = "Chen Yong";
item.properties["acmedl:VL_Telephone"] = "021-57831130";
item.properties["acmedl:VL_MobilePhone"] = "139 1600 1092";
item.properties["acmedl:VL_Email"] = "mailto:yong.chen@ksr-kuebler.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "Beijing Century Longtime International Limited";
item.properties["acmedl:VL_Brand"] = "E+H";
item.properties["acmedl:VL_Contact"] = "pan xuan";
item.properties["acmedl:VL_Telephone"] = "+86 10 6556 5059";
item.properties["acmedl:VL_MobilePhone"] = "152 1016 9146";
item.properties["acmedl:VL_Email"] = "shijilangteng@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "Magnetrol (Shanghai) Co., Ltd";
item.properties["acmedl:VL_Brand"] = "MAGNETROL";
item.properties["acmedl:VL_Contact"] = "Wegri Wang";
item.properties["acmedl:VL_Telephone"] = "021-6249-1350-821";
item.properties["acmedl:VL_MobilePhone"] = "136 0178 6766";
item.properties["acmedl:VL_Email"] = "mailto:wwang@magnetrol.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "Shanghai KSR-KUEBLER Automation Instrument Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "KSR";
item.properties["acmedl:VL_Contact"] = "Ma qingyu";
item.properties["acmedl:VL_Telephone"] = "021-33521288";
item.properties["acmedl:VL_MobilePhone"] = "137 0194 8600";
item.properties["acmedl:VL_Email"] = "mailto:qingyu.ma@ksr-kuebler.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Gauge, Pressure Gauge and Differential Pressure Gauge";
item.properties["acmedl:VL_Company"] = "Ashcroft Instruments(Suzhou) Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "Ashcroft";
item.properties["acmedl:VL_Contact"] = "Zhao Yingying";
item.properties["acmedl:VL_Telephone"] = "+86 10 6556 5059";
item.properties["acmedl:VL_MobilePhone"] = "152 1016 9146";
item.properties["acmedl:VL_Email"] = "mailto:shijilangteng@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter and Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "Beijing Century Longtime International Limited";
item.properties["acmedl:VL_Brand"] = "E+H";
item.properties["acmedl:VL_Contact"] = "Zhao Yingying";
item.properties["acmedl:VL_Telephone"] = "+86 10 6556 5059";
item.properties["acmedl:VL_MobilePhone"] = "152 1016 9146";
item.properties["acmedl:VL_Email"] = "shijilangteng@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter and Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "ABB (China) Limited";
item.properties["acmedl:VL_Brand"] = "ABB";
item.properties["acmedl:VL_Contact"] = "Vicky-Jian.Zhang";
item.properties["acmedl:VL_Telephone"] = "+86 10 64232199";
item.properties["acmedl:VL_MobilePhone"] = "139 1138 2661";
item.properties["acmedl:VL_Email"] = "mailto:vicky-jian.zhang@cn.abb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter and Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "Winters Instruments";
item.properties["acmedl:VL_Brand"] = "Winters";
item.properties["acmedl:VL_Contact"] = "wang peng";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "139 2070 9639";
item.properties["acmedl:VL_Email"] = "mailto:awang@winters.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter and Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "WIKA Beiing office";
item.properties["acmedl:VL_Brand"] = "WIKA";
item.properties["acmedl:VL_Contact"] = "wang shiyu";
item.properties["acmedl:VL_Telephone"] = "010-84545322";
item.properties["acmedl:VL_MobilePhone"] = "186 1136 1169";
item.properties["acmedl:VL_Email"] = "mailto:e.wang@wika.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter and Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "ROSEMOUNT";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-58211000";
item.properties["acmedl:VL_MobilePhone"] = "150 0113 5685";
item.properties["acmedl:VL_Email"] = "mailto:Mingxuan.Xu@Emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Morimatsu USA";
item.properties["acmedl:VL_Brand"] = "Morimatsu";
item.properties["acmedl:VL_Contact"] = "Peng Zhong";
item.properties["acmedl:VL_Telephone"] = "021-38112058-8101";
item.properties["acmedl:VL_MobilePhone"] = "159 2134 1741";
item.properties["acmedl:VL_Email"] = "mailto:zhaoqiao@morimatsu.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam Trap";
item.properties["acmedl:VL_Company"] = "Armstrong china";
item.properties["acmedl:VL_Brand"] = "Armstrong";
item.properties["acmedl:VL_Contact"] = "Yang hai";
item.properties["acmedl:VL_Telephone"] = "010 61255888";
item.properties["acmedl:VL_MobilePhone"] = "138 1156 5072";
item.properties["acmedl:VL_Email"] = "mailto:yangh@armstrong.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam Trap";
item.properties["acmedl:VL_Company"] = "Quko Int'l Development Ltd. (Gestra)";
item.properties["acmedl:VL_Brand"] = "Gestra";
item.properties["acmedl:VL_Contact"] = "Jiang weixiong";
item.properties["acmedl:VL_Telephone"] = "010-85779933";
item.properties["acmedl:VL_MobilePhone"] = "139 1113 8328";
item.properties["acmedl:VL_Email"] = "mailto:whricky@qutointl.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam Trap";
item.properties["acmedl:VL_Company"] = "Spirax Sarco China";
item.properties["acmedl:VL_Brand"] = "SpiraxSarco";
item.properties["acmedl:VL_Contact"] = "Li Guangqiang";
item.properties["acmedl:VL_Telephone"] = "010-67884655";
item.properties["acmedl:VL_MobilePhone"] = "138 1089 8270";
item.properties["acmedl:VL_Email"] = "mailto:lee.li@cn.spiraxsarco.com";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Pall Filter (Beijing) Co. Ltd.";
item.properties["acmedl:VL_Brand"] = "Pall";
item.properties["acmedl:VL_Contact"] = "Li Zheng";
item.properties["acmedl:VL_Telephone"] = "010-87225588";
item.properties["acmedl:VL_MobilePhone"] = "139 1190 5906";
item.properties["acmedl:VL_Email"] = "michael_zheng_li@ap.pall.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Donaldson Company, Inc";
item.properties["acmedl:VL_Brand"] = "donaldson";
item.properties["acmedl:VL_Contact"] = "Mary Liu";
item.properties["acmedl:VL_Telephone"] = "010-5879-3773";
item.properties["acmedl:VL_MobilePhone"] = "139 1010 9751";
item.properties["acmedl:VL_Email"] = "mary.liu@donaldson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Pentair Process Technologies GBU";
item.properties["acmedl:VL_Brand"] = "Pentair";
item.properties["acmedl:VL_Contact"] = "Coco yang";
item.properties["acmedl:VL_Telephone"] = "010- 64366718-116";
item.properties["acmedl:VL_MobilePhone"] = "139 1158 2491";
item.properties["acmedl:VL_Email"] = "coco.yang@Pentair.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "PSV";
item.properties["acmedl:VL_Company"] = "Farris Engineering - Greater China Sales Office";
item.properties["acmedl:VL_Brand"] = "Farris";
item.properties["acmedl:VL_Contact"] = "Myron Xing";
item.properties["acmedl:VL_Telephone"] = "010-6505 8966";
item.properties["acmedl:VL_MobilePhone"] = "139 0119 1536";
item.properties["acmedl:VL_Email"] = "mxing@curtisswright.com";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "PSV";
item.properties["acmedl:VL_Company"] = "Dresser c/o Shanghai E.K Controls Co. Ltd.";
item.properties["acmedl:VL_Brand"] = "Consolidate";
item.properties["acmedl:VL_Contact"] = "Mr. Lan Hao";
item.properties["acmedl:VL_Telephone"] = "021-5109 5182";
item.properties["acmedl:VL_MobilePhone"] = "137 6105 3263";
item.properties["acmedl:VL_Email"] = "lanny.lan@ekcontrol.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Molecular Sieve";
item.properties["acmedl:VL_Company"] = "W.R. Grace  Ltd";
item.properties["acmedl:VL_Brand"] = "Grace";
item.properties["acmedl:VL_Contact"] = "Feng jian";
item.properties["acmedl:VL_Telephone"] = "021-5467 4678-603";
item.properties["acmedl:VL_MobilePhone"] = "138 1781 9060";
item.properties["acmedl:VL_Email"] = "Jian.Feng@grace.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Molecular Sieve";
item.properties["acmedl:VL_Company"] = "Shanghai UOP  LTD";
item.properties["acmedl:VL_Brand"] = "UOP";
item.properties["acmedl:VL_Contact"] = "Henry Lin";
item.properties["acmedl:VL_Telephone"] = "021-6430 2370-2998";
item.properties["acmedl:VL_MobilePhone"] = "137-0169-0378";
item.properties["acmedl:VL_Email"] = "Henry.lin3@uop.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();


