// Get/Create data list container
// var site = companyhome.childByNamePath("Sites/swsdp");
// var dataListContainer = "dataLists";
// var dataLists = site.getContainer(dataListContainer);
// var site = siteService.getSite("swsdp");
var site = siteService.getSite("vendor-list");
var dataLists = site.getContainer("dataLists");

var vendorListName = "Vendor List";
var vendorList = dataLists.childByNamePath(vendorListName);

var vendorListItemType = "acmedl:VendorListItem";

// Add an item to the vendor list

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Loading Arm";
item.properties["acmedl:VL_Company"] = "FMC Technology S.A.";
item.properties["acmedl:VL_Brand"] = "FMC";
item.properties["acmedl:VL_Contact"] = "Ellen Hao";
item.properties["acmedl:VL_Telephone"] = "010-64323078";
item.properties["acmedl:VL_MobilePhone"] = "13911696099";
item.properties["acmedl:VL_Email"] = "energytrack@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Loading Arm";
item.properties["acmedl:VL_Company"] = "Jiangsu Dewei Machine Co., Ltd.江苏德威机械设备有限公司";
item.properties["acmedl:VL_Brand"] = "Dewei";
item.properties["acmedl:VL_Contact"] = "Wang Xiaoli";
item.properties["acmedl:VL_Telephone"] = "0518-85152237";
item.properties["acmedl:VL_MobilePhone"] = "13675203257";
item.properties["acmedl:VL_Email"] = "dmco@dmco.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "山东艺能锅炉有限责任公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "王得权";
item.properties["acmedl:VL_Telephone"] = "0534-8100810";
item.properties["acmedl:VL_MobilePhone"] = "15053497329";
item.properties["acmedl:VL_Email"] = "sdyngs@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "山东菏泽锅炉厂有限公司 www.hezeguolua.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "罗自华";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15253070990";
item.properties["acmedl:VL_Email"] = "573837685@qq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Hangzhou Fortune Gas Equipment Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "杜宏鹏";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13019724173";
item.properties["acmedl:VL_Email"] = "hongpeng.du@fortune-gas.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Heze Hua Wang High Pressure Vessels Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "任勇辉";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "18905302631";
item.properties["acmedl:VL_Email"] = "18905302631@189.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Suzhou Since Gas System Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "杨怀进";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15305241068";
item.properties["acmedl:VL_Email"] = "yanghuaijin298@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Chart Cryogenic Engineering Systems (Changzhou) Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "王坚强";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13861079788";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Zhangjiagang Hanjung Technology Co., Ltd. ";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Mgr.";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13773236672";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LIQUID NITROGEN STORAGE AND VAPORISING PACKAGE";
item.properties["acmedl:VL_Company"] = "Suzhou HuaFu Cryogenic Vessels Co., Ltd. www.sz-huafu.com.cn";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Xiao Weidong";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13451522101";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "PSV";
item.properties["acmedl:VL_Company"] = "LESER Beijing Office";
item.properties["acmedl:VL_Brand"] = "LESER";
item.properties["acmedl:VL_Contact"] = "Li Wei";
item.properties["acmedl:VL_Telephone"] = "10-84885215";
item.properties["acmedl:VL_MobilePhone"] = "10-84885215";
item.properties["acmedl:VL_Email"] = "leserchina81@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "PSV";
item.properties["acmedl:VL_Company"] = "Zhejiang Chaoda Valves Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "葛晓雷";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13818811587";
item.properties["acmedl:VL_Email"] = "13818811587@139.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ultrasonic flowmeter";
item.properties["acmedl:VL_Company"] = "Endress+Hauser Shanghai Automation Equipment Co. Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "王冶钰";
item.properties["acmedl:VL_Telephone"] = "010-59572888";
item.properties["acmedl:VL_MobilePhone"] = "13601162174 ";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "Beijing Far East Rosemount Instrument Co, Ltd";
item.properties["acmedl:VL_Brand"] = "Rosemount/Emerson";
item.properties["acmedl:VL_Contact"] = "Zhang Li";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "139 1056 8360";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "Endress+Hauser / Endress+Hauser Shanghai Automation Equipment Co. Ltd";
item.properties["acmedl:VL_Brand"] = "E+H";
item.properties["acmedl:VL_Contact"] = "陈振宇";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "13901135722";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Gauge";
item.properties["acmedl:VL_Company"] = "JUMO Automation (Dalian) Co., Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "刘志强";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "18210159098";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Furnace";
item.properties["acmedl:VL_Company"] = "China Chemical Furnace & Kiln Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "China Chemical";
item.properties["acmedl:VL_Contact"] = "Mr. Zhou Ping";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13803004234";
item.properties["acmedl:VL_Email"] = "limei@cntcc.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Furnace";
item.properties["acmedl:VL_Company"] = "Wuxi Huaguang Boiler Co., Ltd无锡华光锅炉股份有限公司";
item.properties["acmedl:VL_Brand"] = "Wuxi Huaguang";
item.properties["acmedl:VL_Contact"] = "Mr. Shao Gengdong";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13306181842";
item.properties["acmedl:VL_Email"] = "wbw@wuxiboiler.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "Shandong Shuanglun Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "韩建辉";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13911030457";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "Shanghai Pacific Pump Manufacture (Group) Co.Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "朱东雷 ";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13485036255";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "Shanghai East Pump(Gr- oup) Co., Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "刘福礼";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13511035796";
item.properties["acmedl:VL_Email"] = "super080107@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Furnace";
item.properties["acmedl:VL_Company"] = "Jiangyin Petrolchemical Equipment Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "Jiangyin Petrolchemical";
item.properties["acmedl:VL_Contact"] = "Sales";
item.properties["acmedl:VL_Telephone"] = "0510-6125788";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "Xylem Inc.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "陈经理";
item.properties["acmedl:VL_Telephone"] = "13817802846";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "Bristol";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = " +9714 347 2426";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "sales@bristol-fire.com";
item.properties["acmedl:VL_Country"] = "Dubai";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Furnace";
item.properties["acmedl:VL_Company"] = "Duiker Combustion Engineers";
item.properties["acmedl:VL_Brand"] = "Duiker";
item.properties["acmedl:VL_Contact"] = "Li Weiqiang";
item.properties["acmedl:VL_Telephone"] = "010-84711038";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "weiqiangli@hofung-technology.com";
item.properties["acmedl:VL_Country"] = "The Netherlands";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire pump";
item.properties["acmedl:VL_Company"] = "NAFFCO";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = " +9714 815 1111";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "info@naffco.ae";
item.properties["acmedl:VL_Country"] = "Dubai";
item.properties["acmedl:VL_Descipline"] = "Plumbing & Firefighting";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Furnace";
item.properties["acmedl:VL_Company"] = "BSS (Beijing) Petro-Chemical Equipment Co.Ltd.碧海舟（北京）石油化工设备有限公司 ";
item.properties["acmedl:VL_Brand"] = "BSS";
item.properties["acmedl:VL_Contact"] = "Zhou Haibo";
item.properties["acmedl:VL_Telephone"] = "010-84898700-819";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "zhb@bss.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "Shanghai Marine";
item.properties["acmedl:VL_Brand"] = "Shanghai Marine";
item.properties["acmedl:VL_Contact"] = "Liu Shijun";
item.properties["acmedl:VL_Telephone"] = "021-31310244";
item.properties["acmedl:VL_MobilePhone"] = "13801705687";
item.properties["acmedl:VL_Email"] = "LSJ711@126.COM";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "ATEA (Shanghai)Environmental Ltd.亚德环保工程(上海)有限公司";
item.properties["acmedl:VL_Brand"] = "ATEA";
item.properties["acmedl:VL_Contact"] = "Yvonne Wang";
item.properties["acmedl:VL_Telephone"] = "021-50946670-1108";
item.properties["acmedl:VL_MobilePhone"] = "13917424707";
item.properties["acmedl:VL_Email"] = "yvonne.wang@atea-et.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "KOCH INDUSTRIES (JOHN ZINK)";
item.properties["acmedl:VL_Brand"] = "JOHN ZINK";
item.properties["acmedl:VL_Contact"] = "Cai Yinghua";
item.properties["acmedl:VL_Telephone"] = "021-62675340";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electric Heater";
item.properties["acmedl:VL_Company"] = "Jiangyin Huaneng Electric江阴华能电热器材有限公司";
item.properties["acmedl:VL_Brand"] = "Jiangyin Huaneng";
item.properties["acmedl:VL_Contact"] = "Han Caihong";
item.properties["acmedl:VL_Telephone"] = "0510-86331695";
item.properties["acmedl:VL_MobilePhone"] = "13121507219";
item.properties["acmedl:VL_Email"] = "hancaihongabc@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electric Heater";
item.properties["acmedl:VL_Company"] = "EXHEAT PTE LTD";
item.properties["acmedl:VL_Brand"] = "EXHEAT";
item.properties["acmedl:VL_Contact"] = "Victor Jiao";
item.properties["acmedl:VL_Telephone"] = "6564964609";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "Victor.Jiao@exheat.com.sg";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electric Heater";
item.properties["acmedl:VL_Company"] = "YOKI-ELECTRIC";
item.properties["acmedl:VL_Brand"] = "YOKI-ELECTRIC";
item.properties["acmedl:VL_Contact"] = "Zhao Zhihui";
item.properties["acmedl:VL_Telephone"] = "0514-88243085";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "zzhui143@tom.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electric Heater";
item.properties["acmedl:VL_Company"] = "Shanghai Aore Electric Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "Shanghai Aore";
item.properties["acmedl:VL_Contact"] = "Dai Yanping";
item.properties["acmedl:VL_Telephone"] = "021-68640265-812";
item.properties["acmedl:VL_MobilePhone"] = "13636564885";
item.properties["acmedl:VL_Email"] = "daiyanping226@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Desuperheater";
item.properties["acmedl:VL_Company"] = "Shanghai Hantai";
item.properties["acmedl:VL_Brand"] = "Shanghai Hantai";
item.properties["acmedl:VL_Contact"] = "Zhu Jie";
item.properties["acmedl:VL_Telephone"] = "021-54495083";
item.properties["acmedl:VL_MobilePhone"] = "13501822217";
item.properties["acmedl:VL_Email"] = "hantai_zhujie@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Desuperheater";
item.properties["acmedl:VL_Company"] = "Hora";
item.properties["acmedl:VL_Brand"] = "Hora";
item.properties["acmedl:VL_Contact"] = "Wu Jia";
item.properties["acmedl:VL_Telephone"] = "010-52088301-208";
item.properties["acmedl:VL_MobilePhone"] = "13501076205";
item.properties["acmedl:VL_Email"] = "wujia@horachina.com";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Desuperheater";
item.properties["acmedl:VL_Company"] = "Fisher-Rosemount China Ltd. Beijing";
item.properties["acmedl:VL_Brand"] = "Fisher-Rosemount ";
item.properties["acmedl:VL_Contact"] = "Emily Zhang";
item.properties["acmedl:VL_Telephone"] = "010-65924528Ext.1109";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "emily.zhang@ap.emersonprocess.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Cryogenic Pump";
item.properties["acmedl:VL_Company"] = "NIKKISO";
item.properties["acmedl:VL_Brand"] = "NIKKISO";
item.properties["acmedl:VL_Contact"] = "Takahiro NISHIJIMA";
item.properties["acmedl:VL_Telephone"] = "81-42-392-3548";
item.properties["acmedl:VL_MobilePhone"] = "81-42-392-3549";
item.properties["acmedl:VL_Email"] = "T.Nishijima@nikkiso.co.jp";
item.properties["acmedl:VL_Country"] = "Japan";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Reciprocating Pump";
item.properties["acmedl:VL_Company"] = "Seko";
item.properties["acmedl:VL_Brand"] = "Seko";
item.properties["acmedl:VL_Contact"] = "Li Wei";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13801387093";
item.properties["acmedl:VL_Email"] = "Vince.li@seko.com";
item.properties["acmedl:VL_Country"] = "Italy";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Shanghai Voit";
item.properties["acmedl:VL_Brand"] = "Voit";
item.properties["acmedl:VL_Contact"] = "Li Yan";
item.properties["acmedl:VL_Telephone"] = "010-87875663";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "huabei@voitu.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Andritz AG";
item.properties["acmedl:VL_Brand"] = "Andritz";
item.properties["acmedl:VL_Contact"] = "Günter Haiden";
item.properties["acmedl:VL_Telephone"] = "43.316.6902-2133";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "guenter.haiden@andritz.com";
item.properties["acmedl:VL_Country"] = "Austria";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Weir Pumps";
item.properties["acmedl:VL_Brand"] = "Weir";
item.properties["acmedl:VL_Contact"] = "Lilly Yang";
item.properties["acmedl:VL_Telephone"] = "021-52588111";
item.properties["acmedl:VL_MobilePhone"] = "13472417481";
item.properties["acmedl:VL_Email"] = "lilly.yang@weirminerals.com";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "ABS Group";
item.properties["acmedl:VL_Brand"] = "ABS";
item.properties["acmedl:VL_Contact"] = "Chong Kit Lee";
item.properties["acmedl:VL_Telephone"] = "46 40 35 04 70";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "kitlee.chong@cardo.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Hayward Tyler Group Ltd";
item.properties["acmedl:VL_Brand"] = "Hayward Tyler";
item.properties["acmedl:VL_Contact"] = "Robyn Lewis";
item.properties["acmedl:VL_Telephone"] = "44 (0)1582 436955";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "robynl@haywardtyler.com";
item.properties["acmedl:VL_Country"] = "UK";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Hidrostal Limited";
item.properties["acmedl:VL_Brand"] = "Hidrostal";
item.properties["acmedl:VL_Contact"] = "Jon Hill";
item.properties["acmedl:VL_Telephone"] = "44 (0)1635 550440";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "Jon.Hill@hidrostal.co.uk";
item.properties["acmedl:VL_Country"] = "UK";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "SPP Pumps Limited (Asia)";
item.properties["acmedl:VL_Brand"] = "SPP";
item.properties["acmedl:VL_Contact"] = "Andy Gan";
item.properties["acmedl:VL_Telephone"] = "(65) 6576 5725";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "solutions@spppumps.com";
item.properties["acmedl:VL_Country"] = "Singapore";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Ruhrpumpen Pump";
item.properties["acmedl:VL_Brand"] = "Ruhrpumpen";
item.properties["acmedl:VL_Contact"] = "Feng Ruiguang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901233299";
item.properties["acmedl:VL_Email"] = "fengrg@ruhrpumpen.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Beijing VP Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "Beijing VP";
item.properties["acmedl:VL_Contact"] = "Zhao Wenji";
item.properties["acmedl:VL_Telephone"] = "010-68185214";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "jsgou@bjvp.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Moret";
item.properties["acmedl:VL_Brand"] = "Moret";
item.properties["acmedl:VL_Contact"] = "Zhou Wei";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13817810471";
item.properties["acmedl:VL_Email"] = "zhwei@ensival-moret.cn";
item.properties["acmedl:VL_Country"] = "France";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "ClydeUnion Pumps";
item.properties["acmedl:VL_Brand"] = "ClydeUnion";
item.properties["acmedl:VL_Contact"] = "Lucy Gao";
item.properties["acmedl:VL_Telephone"] = "65989500-319";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "l.gao@clydeunion.com";
item.properties["acmedl:VL_Country"] = "UK";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Sterling";
item.properties["acmedl:VL_Brand"] = "Sterling";
item.properties["acmedl:VL_Contact"] = "Weidong";
item.properties["acmedl:VL_Telephone"] = "010-59046281";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Winston";
item.properties["acmedl:VL_Brand"] = "Winston";
item.properties["acmedl:VL_Contact"] = "Cui Chunqiang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "ccq777777666666@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "ITT";
item.properties["acmedl:VL_Brand"] = "ITT";
item.properties["acmedl:VL_Contact"] = "Ma yanjun";
item.properties["acmedl:VL_Telephone"] = "021-22082888*6319";
item.properties["acmedl:VL_MobilePhone"] = "13512143424";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "Gardner Denver Ltd";
item.properties["acmedl:VL_Brand"] = "Gardner Denver";
item.properties["acmedl:VL_Contact"] = "Wang Xin";
item.properties["acmedl:VL_Telephone"] = "021-64758958";
item.properties["acmedl:VL_MobilePhone"] = "15821280722";
item.properties["acmedl:VL_Email"] = "w-888888@vip.sohu.com";
item.properties["acmedl:VL_Country"] = "USA";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "Shaanxi Blower Group Co., Ltd";
item.properties["acmedl:VL_Brand"] = "Shaanxi Blower";
item.properties["acmedl:VL_Contact"] = "Tang Xiaolong";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13509181093";
item.properties["acmedl:VL_Email"] = "tanglong98@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "Shenyang Blower Works Group Co., Ltd沈阳鼓风机集团压力容器有限公司";
item.properties["acmedl:VL_Brand"] = "Shenyang Blower";
item.properties["acmedl:VL_Contact"] = "Mr.Zhang";
item.properties["acmedl:VL_Telephone"] = "024-25800558";
item.properties["acmedl:VL_MobilePhone"] = "13704002905";
item.properties["acmedl:VL_Email"] = "zhangy@shengu.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "IHI (ISHIKAWAJIMA HARIMA HEAVY INDUSTRIES )石川岛播磨重工业株式会社";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Guowei";
item.properties["acmedl:VL_Telephone"] = "010-85192586";
item.properties["acmedl:VL_MobilePhone"] = "13901134076";
item.properties["acmedl:VL_Email"] = "ihipekcm@ihipk.com.cn";
item.properties["acmedl:VL_Country"] = "Japan";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "Kobe Steel,Ltd.";
item.properties["acmedl:VL_Brand"] = "Kobe Steel";
item.properties["acmedl:VL_Contact"] = "Wang Ning";
item.properties["acmedl:VL_Telephone"] = "010-51659799-301";
item.properties["acmedl:VL_MobilePhone"] = "13601004946";
item.properties["acmedl:VL_Email"] = "Ning_wang@triastoria.com";
item.properties["acmedl:VL_Country"] = "Sweden";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Centrifugal Compressor";
item.properties["acmedl:VL_Company"] = "Atlas Copco";
item.properties["acmedl:VL_Brand"] = "Atlas Copco";
item.properties["acmedl:VL_Contact"] = "sander.van.spijk";
item.properties["acmedl:VL_Telephone"] = "021-2208-4858";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "sander.van.spijk@cn.altascopco.com";
item.properties["acmedl:VL_Country"] = "Sweden";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "HISAKA";
item.properties["acmedl:VL_Brand"] = "HISAKA";
item.properties["acmedl:VL_Contact"] = "Chen Fei";
item.properties["acmedl:VL_Telephone"] = "021-5211-0701ext.206";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "linqi-sha@hisaka.co.jp";
item.properties["acmedl:VL_Country"] = "Singapore";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Compressor";
item.properties["acmedl:VL_Company"] = "安徽省鸿申压缩机有限公司 www.lpgcompressor.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Li";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13865017091";
item.properties["acmedl:VL_Email"] = "hs959@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "南车玉柴四川发动机股份有限公司YCSR SiChuan Engine CO.,LTD.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "郑杰伦";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13568533555";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "上海科泰电源股份有限公司 www.cooltechsh.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhou Lu to";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13801996489";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "大连机车车辆有限公司 Dalian Locomotive and Rolling Stock CO.,LTD.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Mingguo";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13478729346";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "Fujian Minghui Mech. and Elec. Co., Ltd (Mingpowers) 明辉机电——柴油发电机组";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shao Yongwei";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13811795240";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "ES Germany";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "李昊";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13804007970";
item.properties["acmedl:VL_Email"] = "eversystec@outlook.com";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "ZGPT Diesel Heavy Industry Co.,Ltd. ";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "刘Manager";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15988103788";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "AngloBelgianCorporation (ABC) - (Shanghai Branch)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "李聂";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13818061238";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "Tellhow Sci-tec Co., Ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "熊经理  滕广平";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13911136624";
item.properties["acmedl:VL_Email"] = "xiong2986@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Generator";
item.properties["acmedl:VL_Company"] = "Wartsila";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "彭紫阳";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13911518133";
item.properties["acmedl:VL_Email"] = "ziyang.peng@wartsila.com";
item.properties["acmedl:VL_Country"] = "Finland";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "沈阳陆正重工 www.sy-lz.cn";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Lou";
item.properties["acmedl:VL_Telephone"] = "024-89365236";
item.properties["acmedl:VL_MobilePhone"] = "13704017949";
item.properties["acmedl:VL_Email"] = "louying07@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "无锡金龙石化冶金设备制造有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "0510-85590729";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "wxjlgs@wxjinlong.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "青岛康泰重工机械公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Song Jianping";
item.properties["acmedl:VL_Telephone"] = "0532-87716667";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "songjp_0916@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "江联重工股份有限公司 www.jx-jl.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "邓女士";
item.properties["acmedl:VL_Telephone"] = "0791-8520-4703";
item.properties["acmedl:VL_MobilePhone"] = "13707915390";
item.properties["acmedl:VL_Email"] = "dengrr@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Side Channel Pump";
item.properties["acmedl:VL_Company"] = "Zuwa-Zumpe GmbH  www.zuwa.de";
item.properties["acmedl:VL_Brand"] = "Zuwa";
item.properties["acmedl:VL_Contact"] = "Ulrich Holzner";
item.properties["acmedl:VL_Telephone"] = "+49 8682 8934-36";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "uholzner@zuwa.de";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Side Channel Pump";
item.properties["acmedl:VL_Company"] = "Pfeiffer Vacuum GmbH普华真空技术（上海）有限公司www.pfeiffer-vacuum.de";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "董先生";
item.properties["acmedl:VL_Telephone"] = "021-3393-3940";
item.properties["acmedl:VL_MobilePhone"] = "13816240584";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator;#S&T Heat Exchanger";
item.properties["acmedl:VL_Company"] = "江苏民森机械有限公司www.jsmsjx.cn";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "王女士";
item.properties["acmedl:VL_Telephone"] = "0523-84621288";
item.properties["acmedl:VL_MobilePhone"] = "15861039999";
item.properties["acmedl:VL_Email"] = "zhuxiaojianwo@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "泰州市远望换热设备有限公司www.jsjyyd.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "曹润";
item.properties["acmedl:VL_Telephone"] = "0523-88699968";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator;#S&T Heat Exchanger";
item.properties["acmedl:VL_Company"] = "江苏民丰特种设备制造有限公司www.minfengylrq.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "柏乔军";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15952633151";
item.properties["acmedl:VL_Email"] = "385941224@qq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator;#S&T Heat Exchanger";
item.properties["acmedl:VL_Company"] = "大连保税区石化容器www.shihuarongqi.com";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "李响";
item.properties["acmedl:VL_Telephone"] = "0411-87280738";
item.properties["acmedl:VL_MobilePhone"] = "13352239388";
item.properties["acmedl:VL_Email"] = "lixiang3883@hotmail.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "泰州泰怡热工电器有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "高秀英";
item.properties["acmedl:VL_Telephone"] = "www.tzcyq.com";
item.properties["acmedl:VL_MobilePhone"] = "13952605536";
item.properties["acmedl:VL_Email"] = "tzcyq@tzcyq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "TRANTER";
item.properties["acmedl:VL_Brand"] = "TRANTER";
item.properties["acmedl:VL_Contact"] = "Chen Ying";
item.properties["acmedl:VL_Telephone"] = "010-64379490";
item.properties["acmedl:VL_MobilePhone"] = "1391011351";
item.properties["acmedl:VL_Email"] = "lucy0188@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();




