// Get/Create data list container
// var site = companyhome.childByNamePath("Sites/swsdp");
// var dataListContainer = "dataLists";
// var dataLists = site.getContainer(dataListContainer);
// var site = siteService.getSite("swsdp");
var site = siteService.getSite("vendor-list");
var dataLists = site.getContainer("dataLists");

var vendorListName = "Vendor List";
var vendorList = dataLists.childByNamePath(vendorListName);

var vendorListItemType = "acmedl:VendorListItem";

// Add an item to the vendor list

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Positive displacement pumps";
item.properties["acmedl:VL_Company"] = "Sulzer Dalian Pumps & Compressors Ltd.";
item.properties["acmedl:VL_Brand"] = "Sulzer";
item.properties["acmedl:VL_Contact"] = "Luo Zhanyi";
item.properties["acmedl:VL_Telephone"] = "0411-84402728";
item.properties["acmedl:VL_MobilePhone"] = "13304115956";
item.properties["acmedl:VL_Email"] = "mailto:Zhanyi.Luo@sulzer.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " pump";
item.properties["acmedl:VL_Company"] = "Goulds Pumps Inc. （ITT Industries）";
item.properties["acmedl:VL_Brand"] = "Goulds";
item.properties["acmedl:VL_Contact"] = "Zou Qi";
item.properties["acmedl:VL_Telephone"] = "010-63594970";
item.properties["acmedl:VL_MobilePhone"] = "13901129847";
item.properties["acmedl:VL_Email"] = "zouqi@sw.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " pump";
item.properties["acmedl:VL_Company"] = "KSB Shanghai Pump Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "KSB";
item.properties["acmedl:VL_Contact"] = "Jens Ahlers";
item.properties["acmedl:VL_Telephone"] = "021-64302888-2207";
item.properties["acmedl:VL_MobilePhone"] = "15801773723";
item.properties["acmedl:VL_Email"] = "mailto:jens.ahlers@ksb.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " pump";
item.properties["acmedl:VL_Company"] = "FLOWSERVE";
item.properties["acmedl:VL_Brand"] = "FLOWSERVE";
item.properties["acmedl:VL_Contact"] = "David Ning";
item.properties["acmedl:VL_Telephone"] = "010-59210641";
item.properties["acmedl:VL_MobilePhone"] = "13901116474";
item.properties["acmedl:VL_Email"] = "mailto:DNing@flowserve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = " pump";
item.properties["acmedl:VL_Company"] = "Sulzer Dalian Pumps & Compressors Ltd.";
item.properties["acmedl:VL_Brand"] = "Sulzer";
item.properties["acmedl:VL_Contact"] = "Luo Zhanyi";
item.properties["acmedl:VL_Telephone"] = "0411-84402728";
item.properties["acmedl:VL_MobilePhone"] = "13304115956";
item.properties["acmedl:VL_Email"] = "mailto:Zhanyi.Luo@sulzer.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Cold box";
item.properties["acmedl:VL_Company"] = "Chart Industries, Inc.";
item.properties["acmedl:VL_Brand"] = "Chart";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "001-281-364-8700";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Molecular Sieve";
item.properties["acmedl:VL_Company"] = "UOP LLC";
item.properties["acmedl:VL_Brand"] = "UOP";
item.properties["acmedl:VL_Contact"] = "Liu Weiwang";
item.properties["acmedl:VL_Telephone"] = "021-64302370-2978";
item.properties["acmedl:VL_MobilePhone"] = "15900771958";
item.properties["acmedl:VL_Email"] = "mailto:weison.liu@uop.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Wuxi General Chemical Equipment Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "WGC";
item.properties["acmedl:VL_Contact"] = "Cao Honghai";
item.properties["acmedl:VL_Telephone"] = "0510-5632888";
item.properties["acmedl:VL_MobilePhone"] = "13506187799";
item.properties["acmedl:VL_Email"] = "caoh@chemwgcep.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Pentair Filter";
item.properties["acmedl:VL_Brand"] = "Pentair";
item.properties["acmedl:VL_Contact"] = "li Jianzhong";
item.properties["acmedl:VL_Telephone"] = "010-";
item.properties["acmedl:VL_MobilePhone"] = "13811659723";
item.properties["acmedl:VL_Email"] = "mailto:Bill.li@pentair.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Wuxi General Chemical Equipment Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "WGC";
item.properties["acmedl:VL_Contact"] = "Cao Honghai";
item.properties["acmedl:VL_Telephone"] = "0510-5632888";
item.properties["acmedl:VL_MobilePhone"] = "13506187799";
item.properties["acmedl:VL_Email"] = "caoh@chemwgcep.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Yongsheng Machinary Industrial (Kunshan) Co., Ltd";
item.properties["acmedl:VL_Brand"] = "Yongsheng";
item.properties["acmedl:VL_Contact"] = "Han Chunjiu";
item.properties["acmedl:VL_Telephone"] = "0512-57451988-15";
item.properties["acmedl:VL_MobilePhone"] = "13812898952";
item.properties["acmedl:VL_Email"] = "mailto:sdgahg@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Shanghai Yangyuan Pressure Vessel Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "Yangyuan";
item.properties["acmedl:VL_Contact"] = "Zhou Jichen";
item.properties["acmedl:VL_Telephone"] = "021-68480028";
item.properties["acmedl:VL_MobilePhone"] = "13917843237";
item.properties["acmedl:VL_Email"] = "mailto:gingertotti@hotmail.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Shanghai Morimatsu Chemical Equipment Co.,Ltd";
item.properties["acmedl:VL_Brand"] = "Morimatsu";
item.properties["acmedl:VL_Contact"] = "Zhao Qiao";
item.properties["acmedl:VL_Telephone"] = "021-3811 2058-8136";
item.properties["acmedl:VL_MobilePhone"] = "15821649350";
item.properties["acmedl:VL_Email"] = "mailto:18870@vip.sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Cooler";
item.properties["acmedl:VL_Company"] = "Wuxi General Chemical Equipment Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Cao Honghai";
item.properties["acmedl:VL_Telephone"] = "0510-5632888";
item.properties["acmedl:VL_MobilePhone"] = "13506187799";
item.properties["acmedl:VL_Email"] = "caoh@chemwgcep.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Cooler";
item.properties["acmedl:VL_Company"] = "Jord International";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "maxiang";
item.properties["acmedl:VL_Telephone"] = "010-6445 9331";
item.properties["acmedl:VL_MobilePhone"] = "13601328914";
item.properties["acmedl:VL_Email"] = "mailto:mma@jord.com.au";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Schneider Electric (China) Investment Co., Ltd. Shanghai Branch 施耐德电气（中国）投资有限公司上海分公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Liu Zhifeng 刘志峰";
item.properties["acmedl:VL_Telephone"] = "021-24012500";
item.properties["acmedl:VL_MobilePhone"] = "13917266900";
item.properties["acmedl:VL_Email"] = "zhifeng-steven.liu@cn.schneider-electric.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Honeywell Automation and Control Solutions 霍尼韦尔自动化控制系统集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Simon Que 阙浩翔";
item.properties["acmedl:VL_Telephone"] = "021-22196441";
item.properties["acmedl:VL_MobilePhone"] = "13818787250";
item.properties["acmedl:VL_Email"] = "simon.que@honeywell.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Johnson Controls Co., Ltd. 美国江森自控有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Hu Changyong";
item.properties["acmedl:VL_Telephone"] = "010-59281888";
item.properties["acmedl:VL_MobilePhone"] = "13693567183";
item.properties["acmedl:VL_Email"] = "changyong.hu@jci.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Earthing Materials";
item.properties["acmedl:VL_Company"] = "Shanghai Dragon Industrial Engineering Co.,ltd Dragon Industrial Group H.K. Limited 上海爵格工业工程有限公司/爵格工业集团(香港)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liao Zhijun";
item.properties["acmedl:VL_Telephone"] = "021-38870115-818";
item.properties["acmedl:VL_MobilePhone"] = "13681656717";
item.properties["acmedl:VL_Email"] = "liaozj@dragonindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Earthing Materials";
item.properties["acmedl:VL_Company"] = "华厦防雷 (?? To be confirmed)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "BaoWenjiong";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13905162545";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Earthing Materials";
item.properties["acmedl:VL_Company"] = "Hebei Dolong tech Co.,ltd 得龙电气";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Nan Zhengguo";
item.properties["acmedl:VL_Telephone"] = "010-58220996";
item.properties["acmedl:VL_MobilePhone"] = "13801013446";
item.properties["acmedl:VL_Email"] = "nan@dolongtech.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Cable Gland (E&I)";
item.properties["acmedl:VL_Company"] = "Cooper";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Fangqin";
item.properties["acmedl:VL_Telephone"] = "010-65670670";
item.properties["acmedl:VL_MobilePhone"] = "13501277195";
item.properties["acmedl:VL_Email"] = "fangqin.liu@cooperasia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Cable Tray (E&I)";
item.properties["acmedl:VL_Company"] = "DaQo Group Co., Ltd  大全集团有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu Yang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13816175029";
item.properties["acmedl:VL_Email"] = "mailto:yuyang@daquan.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Cable Tray (E&I)";
item.properties["acmedl:VL_Company"] = "Suzhou Ontop Mechanical & Electrical Equipment Co., Ltd. 苏州万拓机电设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wang Lijiang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901657589";
item.properties["acmedl:VL_Email"] = "mailto:ontop@ontopsh.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "STAHL CraneSystems (Shanghai) Co., Ltd.  斯泰尔起重设备贸易(上海)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Killy CHEN 陈姗姗";
item.properties["acmedl:VL_Telephone"] = "021-66083015";
item.properties["acmedl:VL_MobilePhone"] = "159 0169 5779";
item.properties["acmedl:VL_Email"] = "mailto:killy.chen@stahlcarnes.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Verlinde Lifting Equipment 上海法兰特起重机械设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Steven Gu";
item.properties["acmedl:VL_Telephone"] = "021-5889 5533";
item.properties["acmedl:VL_MobilePhone"] = "13818808723";
item.properties["acmedl:VL_Email"] = "stevengu@eurocrane.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Columbus Mckinnon 科美上海分公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Peng Cheng";
item.properties["acmedl:VL_Telephone"] = "021-38820620";
item.properties["acmedl:VL_MobilePhone"] = "13901858074";
item.properties["acmedl:VL_Email"] = "noel.peng@cmworks.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Nanjing Hoisting Machinery General Works 南京起重机械总厂";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wu Xiaojian";
item.properties["acmedl:VL_Telephone"] = "025-85503985";
item.properties["acmedl:VL_MobilePhone"] = "13605189401";
item.properties["acmedl:VL_Email"] = "wuxiao9111@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Hoist";
item.properties["acmedl:VL_Company"] = "Konecranes (Shanghai) Co., Ltd.  科尼起重机设备(上海)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Gloria WEN 文煜";
item.properties["acmedl:VL_Telephone"] = "021-6662 9999 ext. 256";
item.properties["acmedl:VL_MobilePhone"] = "138 1688 4382";
item.properties["acmedl:VL_Email"] = "mailto:gloria.wen@konecranes.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Compressor";
item.properties["acmedl:VL_Company"] = "KOBELCO";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lu Min Zhang Yu";
item.properties["acmedl:VL_Telephone"] = "021-39966391";
item.properties["acmedl:VL_MobilePhone"] = "13818802784 15901657063";
item.properties["acmedl:VL_Email"] = "mailto:lumin@sh-kobelco.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Compressor";
item.properties["acmedl:VL_Company"] = "BOGO";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Andy Zhu Wang Lili Lei Meixi";
item.properties["acmedl:VL_Telephone"] = "021-51688860 010-59046161-280";
item.properties["acmedl:VL_MobilePhone"] = "13381995215 13482857792 13522589092";
item.properties["acmedl:VL_Email"] = "mailto:a.zhu@bogede";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Compressor";
item.properties["acmedl:VL_Company"] = "Wuxi-Atlas Copco Compressor Co., Ltd 无锡阿特拉斯·科普柯压缩机有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Jiang Long Chen MengZhi Wan Yao";
item.properties["acmedl:VL_Telephone"] = "022-58782896 010-65280517";
item.properties["acmedl:VL_MobilePhone"] = "13511050097 15802264808 15901116825";
item.properties["acmedl:VL_Email"] = "mailto:13511050097@139.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Compressor";
item.properties["acmedl:VL_Company"] = "Kaeser(JV) 凯撒空压机（上 海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Jerry Feng";
item.properties["acmedl:VL_Telephone"] = "021-54422666-203";
item.properties["acmedl:VL_MobilePhone"] = "13816110473";
item.properties["acmedl:VL_Email"] = "mailto:Jerry.feng@kaeser.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Compressor";
item.properties["acmedl:VL_Company"] = "Shanghai Ingersoll-Rand Compressor Ltd. 上海英格索兰压缩机有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mars Gao  Zhu Gang";
item.properties["acmedl:VL_Telephone"] = "010-67526012 025-86565033";
item.properties["acmedl:VL_MobilePhone"] = "13910383706 13817694052";
item.properties["acmedl:VL_Email"] = "mailto:Mars_Gao@ap.irco.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Jiangsu Haishi Pumps Manufacturing Co.,Ltd. 江苏海狮泵业制造有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wang Jidong Wen Li";
item.properties["acmedl:VL_Telephone"] = "021-56553030";
item.properties["acmedl:VL_MobilePhone"] = "13505261656 13951142177";
item.properties["acmedl:VL_Email"] = "mailto:wenli56281@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "GRUNDFOS Pumps (Shanghai) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Johnnie He 何斌";
item.properties["acmedl:VL_Telephone"] = "021-61225257";
item.properties["acmedl:VL_MobilePhone"] = "13701604610";
item.properties["acmedl:VL_Email"] = "mailto:jhe@grundfos.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "KSB Shanghai Pump Co. Ltd. 上海凯士比泵有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Kui";
item.properties["acmedl:VL_Telephone"] = "021-6485 7597";
item.properties["acmedl:VL_MobilePhone"] = "18621581599";
item.properties["acmedl:VL_Email"] = "kui.li@ksb.com.cn yong.bian@ksb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Dalian Deep Blue Pump Co., Ltd 大连深蓝泵业有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen GuangBing";
item.properties["acmedl:VL_Telephone"] = "010-64976595 010-64955410";
item.properties["acmedl:VL_MobilePhone"] = "13591777039";
item.properties["acmedl:VL_Email"] = "mailto:Shenguangbing555@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "Shanghai Tonghua Stainless Steel Pressure Vessel Engineering Co., Ltd 上海通华不锈钢压力容器有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Huang Yan";
item.properties["acmedl:VL_Telephone"] = "021-68466855-3049";
item.properties["acmedl:VL_MobilePhone"] = "13167149623";
item.properties["acmedl:VL_Email"] = "huangyan@tonghua-china.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "Jiangsu Sunpower Machinery Manufacture Co., Ltd 江苏中圣机械制造有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Mingde";
item.properties["acmedl:VL_Telephone"] = "010-64705609";
item.properties["acmedl:VL_MobilePhone"] = "13581922792";
item.properties["acmedl:VL_Email"] = "Limd88@hotmail.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "SMEC(Nanjing Special Metal Equipment Co., Ltd ) 南京斯迈柯特种金属装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Tony Zhang(张林  Zhu Yan";
item.properties["acmedl:VL_Telephone"] = "025-5272 3875";
item.properties["acmedl:VL_MobilePhone"] = "13776681872 13770308977";
item.properties["acmedl:VL_Email"] = "mailto:julia.zhu@nsme.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "Zhangjiagang Furui Special Equipment Co.,Ltd  张家港富瑞特种装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Sun He";
item.properties["acmedl:VL_Telephone"] = "0512-58730679";
item.properties["acmedl:VL_MobilePhone"] = "18261858622";
item.properties["acmedl:VL_Email"] = "mailto:sh@furuise.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "Kunshan Bexcelle Special Equipment Co.,Ltd 昆山市贝色特材装备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Luo Ming Peng Fei";
item.properties["acmedl:VL_Telephone"] = "0512-57270788 0512-55011635";
item.properties["acmedl:VL_MobilePhone"] = "13061682252";
item.properties["acmedl:VL_Email"] = "lilyluo@ksbsec.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel";
item.properties["acmedl:VL_Company"] = "Shanghai Morimatsu Pressure Vessel Co., Ltd. 上海森松压力容器有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhao Qiao Peng Zhong";
item.properties["acmedl:VL_Telephone"] = "021-38112058-8008 021-38112058-8101";
item.properties["acmedl:VL_MobilePhone"] = "15821649350 15921341741";
item.properties["acmedl:VL_Email"] = "mailto:zhaoqiao@morimatsu.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam trap, C.S. (20#)";
item.properties["acmedl:VL_Company"] = "Armstrong 阿姆斯壮";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "许婧";
item.properties["acmedl:VL_Telephone"] = "010 61255862";
item.properties["acmedl:VL_MobilePhone"] = "13811565072";
item.properties["acmedl:VL_Email"] = "mailto:xuj@armstrong.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam trap, C.S. (20#)";
item.properties["acmedl:VL_Company"] = "Quko Int'l Development Ltd. (Gestra)  翘高国际发展有限公司(杰斯特拉代理)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr.Zhao";
item.properties["acmedl:VL_Telephone"] = "021-64870493";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Steam trap, C.S. (20#)";
item.properties["acmedl:VL_Company"] = "Spirax Sarco China 斯派莎克工程（中国）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Guangqiang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13810898270";
item.properties["acmedl:VL_Email"] = "mailto:lee.li@cn.spiraxsarco.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Shower";
item.properties["acmedl:VL_Company"] = "Unite Great Purification Equipment (Shanghai) Co., Ltd.  统钜净化设备(上海)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Teng YANG";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "139 1886 4657";
item.properties["acmedl:VL_Email"] = "mailto:yt@ugp-sh.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Shower";
item.properties["acmedl:VL_Company"] = "Shenzhen Juxing Purification Technology Co., Ltd.  深圳市巨星净化科技有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Chao WU";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13760134150";
item.properties["acmedl:VL_Email"] = "mailto:juxing2000@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Shower";
item.properties["acmedl:VL_Company"] = "Shanghai Karsten Cleanroom Materials Co.,Ltd.  上海卡斯特环境净化材料有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Linda XU";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "139 0166 0779";
item.properties["acmedl:VL_Email"] = "linda@kcscn.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Shower";
item.properties["acmedl:VL_Company"] = "Suzhou Shinsung ENG Co., Ltd.   苏州新盛超净化系统有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Yuebing WAN";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "139 1370 3581";
item.properties["acmedl:VL_Email"] = "wyb@shinsung.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Shower";
item.properties["acmedl:VL_Company"] = "Suzhou Futai Clean Systems Co., Ltd.   苏州富泰洁净系统有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Mei XU徐梅";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "135 8586 9858";
item.properties["acmedl:VL_Email"] = "13585869858@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety Shower & Eye Washer";
item.properties["acmedl:VL_Company"] = "Jiangsu Dragon Industrial Equipment Co., Ltd. 江苏爵格工业设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "lichaogang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "135 2205 2648";
item.properties["acmedl:VL_Email"] = "mailto:licg@dragonindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety Shower & Eye Washer";
item.properties["acmedl:VL_Company"] = "Wuxi STG Safety Equipment Co., Ltd. 无锡斯壮格安全设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Xiaolin LIU";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:wx@stgmfg.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Safety Shower & Eye Washer";
item.properties["acmedl:VL_Company"] = "Zhejiang Xulong Machine Industry Co.,Ltd. 浙江旭龙机械工业有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:zhengjx@chinaxulong.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "U/G Gaskets";
item.properties["acmedl:VL_Company"] = "Garlock Sealing Technologies (Shanghai) Co., Ltd. 卡勒克密封技术（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Fang WU";
item.properties["acmedl:VL_Telephone"] = "021-64544412";
item.properties["acmedl:VL_MobilePhone"] = "13816306493";
item.properties["acmedl:VL_Email"] = "fang.wu@garlock.com; suhua.xiao@garlock.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gasket";
item.properties["acmedl:VL_Company"] = "Shanghai Zone Gasket Co., Ltd.  上海瑞欧密封材料有限公司 (Flexitallic)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Yalun XU";
item.properties["acmedl:VL_Telephone"] = "021-58128117";
item.properties["acmedl:VL_MobilePhone"] = "13701817782";
item.properties["acmedl:VL_Email"] = "mailto:alan.zone@vip.163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gasket";
item.properties["acmedl:VL_Company"] = "IDT Sinyuan Sealing Technology Co.,Ltd. 宁波易天地信远密封技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Wei GONG";
item.properties["acmedl:VL_Telephone"] = "021-64812722";
item.properties["acmedl:VL_MobilePhone"] = "13916576731";
item.properties["acmedl:VL_Email"] = "w.gong@iss-gasket.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gasket";
item.properties["acmedl:VL_Company"] = "Garlock Sealing Technologies (Shanghai) Co., Ltd. 卡勒克密封技术（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Fang WU";
item.properties["acmedl:VL_Telephone"] = "021-64544412";
item.properties["acmedl:VL_MobilePhone"] = "13816306493";
item.properties["acmedl:VL_Email"] = "fang.wu@garlock.com; suhua.xiao@garlock.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flanges";
item.properties["acmedl:VL_Company"] = "Shanxi Guanjiaying Forging Flange Co.,Ltd.  山西管家营法兰锻造有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "TAN Hongwei";
item.properties["acmedl:VL_Telephone"] = "0351-6287643;  0350-6086262;  0351-6273736";
item.properties["acmedl:VL_MobilePhone"] = "13935034025;  13803446425";
item.properties["acmedl:VL_Email"] = "petervean@yahoo.com.cn;  t1970hw@yahoo.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "U/G Pipe Fitting & Flange";
item.properties["acmedl:VL_Company"] = "Jiangsu Huayang Metal Pipe & Fittings Co., Ltd.  江苏华阳金属管件有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "BIAN Minghua";
item.properties["acmedl:VL_Telephone"] = "0511-87287228";
item.properties["acmedl:VL_MobilePhone"] = "13916907291";
item.properties["acmedl:VL_Email"] = "mailto:steven@hymco.com (SS only)";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "U/G Pipe Fitting & Flange";
item.properties["acmedl:VL_Company"] = "Jiangyin Nanfang Pipe Fitting Making Company Ltd.  江阴市南方管件制造有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Huang Guohong";
item.properties["acmedl:VL_Telephone"] = "0510-86133999";
item.properties["acmedl:VL_MobilePhone"] = "13806165351";
item.properties["acmedl:VL_Email"] = "mailto:nff@nfgj.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "A/G Pipe Fitting (CS & SS)";
item.properties["acmedl:VL_Company"] = "Yangzhou Pipe Fitting Factory Co., Ltd.  扬州市管件厂有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Jiang Wen";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13501638518";
item.properties["acmedl:VL_Email"] = "mailto:webmaster@yzsgjc.com (CS only)";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Post Indicator Valve";
item.properties["acmedl:VL_Company"] = "Tyco Flow Control (Beijing) Co,.Ltd. 泰科流体控制（北京）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yan Min";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15900955892";
item.properties["acmedl:VL_Email"] = "ranyan@tyco-valves.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Post Indicator Valve";
item.properties["acmedl:VL_Company"] = "Neway Valve (Suzhou)  Co., Ltd. 苏州纽威阀门股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Qiao Jin";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15050158266";
item.properties["acmedl:VL_Email"] = "mailto:Jin.Qiao@neway.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Post Indicator Valve";
item.properties["acmedl:VL_Company"] = "博雷(中国)控制系统有限公司 Bray China Controls Co. Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shi Sui";
item.properties["acmedl:VL_Telephone"] = "010 65669232";
item.properties["acmedl:VL_MobilePhone"] = "13910767273";
item.properties["acmedl:VL_Email"] = "mailto:William.shi@bray.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Alarm System ";
item.properties["acmedl:VL_Company"] = "Tyco Fire & Security (Tianjin) Co., Ltd.  泰科消防保安（天津）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "He Jingwen";
item.properties["acmedl:VL_Telephone"] = "010-65693200-5186";
item.properties["acmedl:VL_MobilePhone"] = "13901353229";
item.properties["acmedl:VL_Email"] = "jwhe@tycoint.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Alarm System ";
item.properties["acmedl:VL_Company"] = "Nanjing Fire Protection Technology 南京消防器材股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Qiu, ZhiHeng (Josh) 仇智珩";
item.properties["acmedl:VL_Telephone"] = "025-84878638";
item.properties["acmedl:VL_MobilePhone"] = "13505140234";
item.properties["acmedl:VL_Email"] = "qiuzhiheng@tuna.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Alarm System ";
item.properties["acmedl:VL_Company"] = "Beijing Lida Aisheng (BJ) 北京利达爱生电子技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "林利琴";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13718180931";
item.properties["acmedl:VL_Email"] = "mailto:enscience@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Alarm System ";
item.properties["acmedl:VL_Company"] = "Honeywell Fire and Security Systems Co., Ltd. 美国霍尼韦尔气体探测有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wu Xinwei";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "18601278158";
item.properties["acmedl:VL_Email"] = "bhyt781@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Component";
item.properties["acmedl:VL_Company"] = "Viking Fire Protection Equipment Trading (Shanghai) Co., Ltd. 威景防火设备贸易（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Hui";
item.properties["acmedl:VL_Telephone"] = "021-62493321";
item.properties["acmedl:VL_MobilePhone"] = "13701915806";
item.properties["acmedl:VL_Email"] = "hshen@vikingcorp.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fire Component";
item.properties["acmedl:VL_Company"] = "Beijing Lida Aisheng Electronics Technology Co. Ltd. 北京利达爱生电子技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhong Wei";
item.properties["acmedl:VL_Telephone"] = "010-59713379";
item.properties["acmedl:VL_MobilePhone"] = "13801167259";
item.properties["acmedl:VL_Email"] = "newleader@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "TYCO 泰科消防保安（天津）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Jingwen HE 何京文";
item.properties["acmedl:VL_Telephone"] = "+86-10-8520 0886";
item.properties["acmedl:VL_MobilePhone"] = "13901353229";
item.properties["acmedl:VL_Email"] = "jwhe@tycoint.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Siemens Building Technologies (Tianjin) Co., Ltd. 西门子楼宇科技（天津）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ms. Jinghong WANG";
item.properties["acmedl:VL_Telephone"] = "010-64767762";
item.properties["acmedl:VL_MobilePhone"] = "13811451300";
item.properties["acmedl:VL_Email"] = "mailto:jinghong.wang@siemens.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Honeywell Automation and Control Solutions 霍尼韦尔自动化控制系统集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Baolin WU";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13911665295";
item.properties["acmedl:VL_Email"] = "mailto:13911665295@139.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Security System (incl. PAS, Radio, Telephone/LAN System)";
item.properties["acmedl:VL_Company"] = "Johnson Controls Co., Ltd. 美国江森自控有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Jun LI";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13661188315;  13391775758";
item.properties["acmedl:VL_Email"] = "mailto:13391775758@189.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Power Cable / Wire";
item.properties["acmedl:VL_Company"] = "Anhui Tiankang (Group) Co., Ltd. 安徽天康（集团）股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu yuancai";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13909600747";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Power Cable / Wire";
item.properties["acmedl:VL_Company"] = "Yangzhou Shuguang Cable Co., Ltd. 扬州曙光电缆有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Power Cable / Wire";
item.properties["acmedl:VL_Company"] = "Suzhou Draka Cable Co., Ltd. 苏州特雷卡电缆有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang fengjun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "sales@draka.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Power Cable / Wire";
item.properties["acmedl:VL_Company"] = "Baosheng Science & Technology Innovation Co., Ltd. 宝胜科技创新股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Xie Hongxia";
item.properties["acmedl:VL_Telephone"] = "010-67348677";
item.properties["acmedl:VL_MobilePhone"] = "13701115365";
item.properties["acmedl:VL_Email"] = "by.fmr@163.net";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Cable";
item.properties["acmedl:VL_Company"] = "Anhui Tiankang (Group) Co., Ltd. 安徽天康（集团）股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu yuancai";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13909600747";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Cable";
item.properties["acmedl:VL_Company"] = "Suzhou Draka Cable Co., Ltd. 苏州特雷卡电缆有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang fengjun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "sales@draka.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();



