// Get/Create data list container
// var site = companyhome.childByNamePath("Sites/swsdp");
// var dataListContainer = "dataLists";
// var dataLists = site.getContainer(dataListContainer);
// var site = siteService.getSite("swsdp");
var site = siteService.getSite("vendor-list");
var dataLists = site.getContainer("dataLists");

var vendorListName = "Vendor List";
var vendorList = dataLists.childByNamePath(vendorListName);

var vendorListItemType = "acmedl:VendorListItem";

// Add an item to the vendor list

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Cable";
item.properties["acmedl:VL_Company"] = "Baosheng Science & Technology Innovation Co., Ltd. 宝胜科技创新股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Xie Hongxia";
item.properties["acmedl:VL_Telephone"] = "010-67348677";
item.properties["acmedl:VL_MobilePhone"] = "13701115365";
item.properties["acmedl:VL_Email"] = "by.fmr@163.net";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "EX-proof Junction Box";
item.properties["acmedl:VL_Company"] = "R.Stahl Ex-Proof (Shanghai) Co., Ltd. 德安防爆电器（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Rao Wei";
item.properties["acmedl:VL_Telephone"] = "010-64241741";
item.properties["acmedl:VL_MobilePhone"] = "13301136929";
item.properties["acmedl:VL_Email"] = "raowei@rstahl.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "EX-proof Junction Box";
item.properties["acmedl:VL_Company"] = "Cooper Crouse-Hinds GMBH 库柏防爆";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Fangqin";
item.properties["acmedl:VL_Telephone"] = "010-65670670";
item.properties["acmedl:VL_MobilePhone"] = "13501277195";
item.properties["acmedl:VL_Email"] = "fangqin.liu@cooperasia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "EX-proof Junction Box";
item.properties["acmedl:VL_Company"] = "Zhejiang Huarong Explosionproof Electric Co.,Ltd. 浙江华荣防爆电器有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wangjiancheng";
item.properties["acmedl:VL_Telephone"] = "025-85073777";
item.properties["acmedl:VL_MobilePhone"] = "13305158163";
item.properties["acmedl:VL_Email"] = "nj@warom.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Normal Lighting Fixtures ";
item.properties["acmedl:VL_Company"] = "R.Stahl Ex-Proof (Shanghai) Co., Ltd. 德安防爆电器（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yang Jinhui";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901463534";
item.properties["acmedl:VL_Email"] = "hengtong@el-ex.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Normal Lighting Fixtures ";
item.properties["acmedl:VL_Company"] = "Cooper Electric (Shanghai) Co., Ltd. 库柏电气(上海)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Fangqin";
item.properties["acmedl:VL_Telephone"] = "010-65670670";
item.properties["acmedl:VL_MobilePhone"] = "13501277195";
item.properties["acmedl:VL_Email"] = "fangqin.liu@cooperasia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Normal Lighting Fixtures ";
item.properties["acmedl:VL_Company"] = "Hebei Dolong tech Co.,Ltd. 得龙电气";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Wei";
item.properties["acmedl:VL_Telephone"] = "010-64764595";
item.properties["acmedl:VL_MobilePhone"] = "13911825395";
item.properties["acmedl:VL_Email"] = "wei.wl.liu@siemens.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Normal Lighting Fixtures ";
item.properties["acmedl:VL_Company"] = "Shanghai Dragon Industrial Engineering Co.,Ltd. 上海爵格工业工程有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr. Chaogang LI";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "135 2205 2648";
item.properties["acmedl:VL_Email"] = "mailto:licg@dragonindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electrical Heat Tracing";
item.properties["acmedl:VL_Company"] = "Tyco Thermal Controls 泰科热控";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Grace Zhang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13910110075";
item.properties["acmedl:VL_Email"] = "grace.zhang@tycothermal.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electrical Heat Tracing";
item.properties["acmedl:VL_Company"] = "Bartec Electric (Shanghai) Co., Ltd. 博太科电气（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "He Ping";
item.properties["acmedl:VL_Telephone"] = "010-58222280-233";
item.properties["acmedl:VL_MobilePhone"] = "13901019801";
item.properties["acmedl:VL_Email"] = "heping@bartec.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Electrical Heat Tracing";
item.properties["acmedl:VL_Company"] = "Thermon Heat Tracing & Engineering Co., Ltd. 赛盟电伴热工程公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Huang Xiaodong Susie Hao(Agent)";
item.properties["acmedl:VL_Telephone"] = "010-84518622 010-64845496";
item.properties["acmedl:VL_MobilePhone"] = "13910317260 13911812772";
item.properties["acmedl:VL_Email"] = "huang_xiaodong@thermonchina.com susie_hao@new-crown.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "UPS ";
item.properties["acmedl:VL_Company"] = "AEG Power Solutions Co., Ltd. 安奕极（北京）电源系统有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu Dong,";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901110484";
item.properties["acmedl:VL_Email"] = "mailto:Dawson.yu@aegps.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "UPS ";
item.properties["acmedl:VL_Company"] = "Schneider Electric (China) Co.Ltd.-GUTOR 施耐德（电气）中国有限公司-Gutor";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mao Yujie";
item.properties["acmedl:VL_Telephone"] = "010-88357897";
item.properties["acmedl:VL_MobilePhone"] = "13601281050";
item.properties["acmedl:VL_Email"] = "mailto:myj2404@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "UPS ";
item.properties["acmedl:VL_Company"] = "Shanghai Emerson Network Power-Chloride   艾默生网络能源公司-Chloride";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ye Hongbing";
item.properties["acmedl:VL_Telephone"] = "021 6875 1326";
item.properties["acmedl:VL_MobilePhone"] = "13917841435";
item.properties["acmedl:VL_Email"] = "mailto:13917841435@139.com；Hongbin.Ye@ChloridePower.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VFD";
item.properties["acmedl:VL_Company"] = "Siemens";
item.properties["acmedl:VL_Brand"] = "Siemens";
item.properties["acmedl:VL_Contact"] = "Mei Bin";
item.properties["acmedl:VL_Telephone"] = "021 54108666-819";
item.properties["acmedl:VL_MobilePhone"] = "13901686461";
item.properties["acmedl:VL_Email"] = "mailto:bin.mei@siemens.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VFD";
item.properties["acmedl:VL_Company"] = "Schneider";
item.properties["acmedl:VL_Brand"] = "Schneider";
item.properties["acmedl:VL_Contact"] = "Wang Shuhai";
item.properties["acmedl:VL_Telephone"] = "021 60657696 ext. 7696";
item.properties["acmedl:VL_MobilePhone"] = "18616855546";
item.properties["acmedl:VL_Email"] = "mailto:shuhai-luke.wang@cn.schneider-electric.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VFD";
item.properties["acmedl:VL_Company"] = "ABB";
item.properties["acmedl:VL_Brand"] = "ABB";
item.properties["acmedl:VL_Contact"] = "Liu Jianghua";
item.properties["acmedl:VL_Telephone"] = "021-23288418";
item.properties["acmedl:VL_MobilePhone"] = "18930872098";
item.properties["acmedl:VL_Email"] = "johnson-jianghua.liu@cn.abb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VFD";
item.properties["acmedl:VL_Company"] = "Danfoss";
item.properties["acmedl:VL_Brand"] = "Danfoss";
item.properties["acmedl:VL_Contact"] = "Luo Hongquan";
item.properties["acmedl:VL_Telephone"] = "010-85352588";
item.properties["acmedl:VL_MobilePhone"] = "13910617818";
item.properties["acmedl:VL_Email"] = "mailto:luohongquan@danfoss.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Transformer";
item.properties["acmedl:VL_Company"] = "Jiangsu Huapeng Transformer Co., Ltd. 江苏华鹏变压器有限公司";
item.properties["acmedl:VL_Brand"] = "Huapeng";
item.properties["acmedl:VL_Contact"] = "Li Chaoqun";
item.properties["acmedl:VL_Telephone"] = "0519-7302414";
item.properties["acmedl:VL_MobilePhone"] = "13921052802";
item.properties["acmedl:VL_Email"] = "13921052802-icq@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Transformer";
item.properties["acmedl:VL_Company"] = "ABB (China) Limited  ABB中国有限公司";
item.properties["acmedl:VL_Brand"] = "ABB";
item.properties["acmedl:VL_Contact"] = "Liu Jianghua";
item.properties["acmedl:VL_Telephone"] = "021-23288418";
item.properties["acmedl:VL_MobilePhone"] = "18930872098";
item.properties["acmedl:VL_Email"] = "johnson-jianghua.liu@cn.abb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Transformer";
item.properties["acmedl:VL_Company"] = "Schneider Electric (China) Co.Ltd.-Sunten 施耐德（电气）中国有限公司-Sunten";
item.properties["acmedl:VL_Brand"] = "Schneider";
item.properties["acmedl:VL_Contact"] = "Sun Zhiqiao";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13510851850";
item.properties["acmedl:VL_Email"] = "zhiqiao-viki.sun@cn.schneider-electric.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Transformer";
item.properties["acmedl:VL_Company"] = "SIEMENS Ltd., China 西门子中国有限公司";
item.properties["acmedl:VL_Brand"] = "SIEMENS";
item.properties["acmedl:VL_Contact"] = "Wang Yu";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13511033986";
item.properties["acmedl:VL_Email"] = "mailto:wangyu.wy@siemens.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Junction Box, Position Switch, Local explosion proof control box, push button";
item.properties["acmedl:VL_Company"] = "R.Stahl Ex-Proof (Shanghai) Co., Ltd. 德安防爆电器（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "R.Stahl";
item.properties["acmedl:VL_Contact"] = "Rao Wei";
item.properties["acmedl:VL_Telephone"] = "010-64241741";
item.properties["acmedl:VL_MobilePhone"] = "13301136929";
item.properties["acmedl:VL_Email"] = "mailto:raowei@rstahl.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Junction Box, Position Switch, Local explosion proof control box, push button";
item.properties["acmedl:VL_Company"] = "Cooper Crouse-Hinds GMBH 库柏防爆";
item.properties["acmedl:VL_Brand"] = "Cooper";
item.properties["acmedl:VL_Contact"] = "Liu Fangqin";
item.properties["acmedl:VL_Telephone"] = "010-65670670";
item.properties["acmedl:VL_MobilePhone"] = "13501277195";
item.properties["acmedl:VL_Email"] = "mailto:fangqin.liu@cooperasia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Junction Box, Position Switch, Local explosion proof control box, push button";
item.properties["acmedl:VL_Company"] = "Zhejiang Huarong Explosionproof Electric Co.,Ltd. 浙江华荣防爆电器有限公司";
item.properties["acmedl:VL_Brand"] = "Huarong";
item.properties["acmedl:VL_Contact"] = "Wangjiancheng";
item.properties["acmedl:VL_Telephone"] = "025-85073777";
item.properties["acmedl:VL_MobilePhone"] = "13305158163";
item.properties["acmedl:VL_Email"] = "mailto:nj@warom.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Junction Box, Position Switch, Local explosion proof control box, push button";
item.properties["acmedl:VL_Company"] = "Bartec Electric (Shanghai) Co., Ltd. 博太科电气（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "Bartec";
item.properties["acmedl:VL_Contact"] = "He Ping";
item.properties["acmedl:VL_Telephone"] = "010-58222280-233";
item.properties["acmedl:VL_MobilePhone"] = "13901019801";
item.properties["acmedl:VL_Email"] = "mailto:heping@bartec.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Instrument Cable (incl control cable)";
item.properties["acmedl:VL_Company"] = "Baosheng Group Co., Ltd. 宝胜集团有限公司";
item.properties["acmedl:VL_Brand"] = "Baosheng";
item.properties["acmedl:VL_Contact"] = "Xie Hongxia";
item.properties["acmedl:VL_Telephone"] = "010-67348677";
item.properties["acmedl:VL_MobilePhone"] = "13701115365";
item.properties["acmedl:VL_Email"] = "mailto:by.fmr@163.net";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Instrument Cable (incl control cable)";
item.properties["acmedl:VL_Company"] = "JiangSu Huayu江苏华宇电缆有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang yueming";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:sales@huacable.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Instrument Cable (incl control cable)";
item.properties["acmedl:VL_Company"] = "Suzhou DRAKA 苏州特雷卡电缆有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang fengjun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:sales@draka.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Instrument Cable (incl control cable)";
item.properties["acmedl:VL_Company"] = "Changzhou Bayi Cables Co., Ltd. 常州八益电缆集团有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chang Guorong";
item.properties["acmedl:VL_Telephone"] = "010-64960649";
item.properties["acmedl:VL_MobilePhone"] = "13691340556";
item.properties["acmedl:VL_Email"] = "mailto:cgr@81cable.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Tube,Tube Fitting & Tube Valve";
item.properties["acmedl:VL_Company"] = "PARKER";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Tube,Tube Fitting & Tube Valve";
item.properties["acmedl:VL_Company"] = "Hoke";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yin Min";
item.properties["acmedl:VL_Telephone"] = "021-50275605 Ext.18";
item.properties["acmedl:VL_MobilePhone"] = "13801914290";
item.properties["acmedl:VL_Email"] = "yinmin@hg-shanghai.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Tube,Tube Fitting & Tube Valve";
item.properties["acmedl:VL_Company"] = "Swagelok";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shi Weimin";
item.properties["acmedl:VL_Telephone"] = "021-61826213";
item.properties["acmedl:VL_MobilePhone"] = "13916500833";
item.properties["acmedl:VL_Email"] = "shi.weimin@swagelok.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Distributor";
item.properties["acmedl:VL_Company"] = "HG Machinery & Electronic Equipment (HK) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Distributor";
item.properties["acmedl:VL_Company"] = "Shanghai Haowei Mechanical & Electrical Equipment Co., Ltd.上海皓蔚机电设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Distributor";
item.properties["acmedl:VL_Company"] = "Shanghai Yangchang Industrial Equipment Co., Ltd. 上海洋畅工业设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Distributor";
item.properties["acmedl:VL_Company"] = "zhangjiagang Hongtai  张家港市泓泰工业设备安装维修有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Rotometer";
item.properties["acmedl:VL_Company"] = "Yokogawa China Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Sun Gaoxiang";
item.properties["acmedl:VL_Telephone"] = "021-62396262 - 3049";
item.properties["acmedl:VL_MobilePhone"] = "13916609556";
item.properties["acmedl:VL_Email"] = "gaoxiang.sun@cn.yokogawa.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Rotometer";
item.properties["acmedl:VL_Company"] = "Krohne measurement instrument(Shanghai) Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Jianzheng";
item.properties["acmedl:VL_Telephone"] = "021-64705656";
item.properties["acmedl:VL_MobilePhone"] = "13916323851";
item.properties["acmedl:VL_Email"] = "jeff.shen@krohne-asia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flowmeter ";
item.properties["acmedl:VL_Company"] = "Krohne measurement instrument(Shanghai) Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Jianzheng";
item.properties["acmedl:VL_Telephone"] = "021-64705656";
item.properties["acmedl:VL_MobilePhone"] = "13916323851";
item.properties["acmedl:VL_Email"] = "jeff.shen@krohne-asia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flowmeter ";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "Liu Zhiyong";
item.properties["acmedl:VL_Telephone"] = "021-28929212";
item.properties["acmedl:VL_MobilePhone"] = "13331901640";
item.properties["acmedl:VL_Email"] = "Marine.Liu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flowmeter ";
item.properties["acmedl:VL_Company"] = "Endress + Hauser Shanghai Automation Equipment Co., Ltd. 上海恩德斯豪斯自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Yang";
item.properties["acmedl:VL_Telephone"] = "010-59572922";
item.properties["acmedl:VL_MobilePhone"] = "13501390765";
item.properties["acmedl:VL_Email"] = "Yang.chen@cn.endress.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Clamp";
item.properties["acmedl:VL_Company"] = "Hebei Dolong tech Co.,Ltd. 得龙电气";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Nan Zhengguo";
item.properties["acmedl:VL_Telephone"] = "010-58220996";
item.properties["acmedl:VL_MobilePhone"] = "13801013446";
item.properties["acmedl:VL_Email"] = "nan@dolongtech.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Clamp";
item.properties["acmedl:VL_Company"] = "Shanghai Dragon Industrial Engineering Co.,Ltd. Dragon Industrial Group H.K. Limited 上海爵格工业工程有限公司/爵格工业集团(香港)有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liao Zhijun";
item.properties["acmedl:VL_Telephone"] = "021-38870115-818";
item.properties["acmedl:VL_MobilePhone"] = "13681656717";
item.properties["acmedl:VL_Email"] = "mailto:liaozj@dragonindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Clamp";
item.properties["acmedl:VL_Company"] = "Cooper Electric (Shanghai) Co., ltd";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Allen Han";
item.properties["acmedl:VL_Telephone"] = "021 2899 4172";
item.properties["acmedl:VL_MobilePhone"] = "13818012692";
item.properties["acmedl:VL_Email"] = "mailto:allen.han@cooperindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Clamp";
item.properties["acmedl:VL_Company"] = "Shanghai Haoyan International Trade Co.,Ltd – Newson Gale";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Macco Yong";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13801610242";
item.properties["acmedl:VL_Email"] = "mailto:Macco@haoyan.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Grounding Clamp";
item.properties["acmedl:VL_Company"] = "Saga International Holding Co., Ltd. 上海复睿工贸有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lv Tao";
item.properties["acmedl:VL_Telephone"] = "021-60917695";
item.properties["acmedl:VL_MobilePhone"] = "13818833172";
item.properties["acmedl:VL_Email"] = "tony@saga-industries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gas Detector";
item.properties["acmedl:VL_Company"] = "Honeywell Fire and Security Systems Co., Ltd. 美国霍尼韦尔气体探测有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wu Xinwei";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "18601278158";
item.properties["acmedl:VL_Email"] = "mailto:bhyt781@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gas Detector";
item.properties["acmedl:VL_Company"] = "MSA(China) Safety Equipment Co., Ltd.   MSA（中国）安全设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Cathy le";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13910009973";
item.properties["acmedl:VL_Email"] = "lehaiya@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Gas Detector";
item.properties["acmedl:VL_Company"] = "Beijing Fortune Dr?ger Safety Equipment Co.,Ltd. 北京吉祥德尔格安全设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Tang Mengmeng";
item.properties["acmedl:VL_Telephone"] = "010 80498000-127";
item.properties["acmedl:VL_MobilePhone"] = "13511013426";
item.properties["acmedl:VL_Email"] = "mailto:Meng.Tang@draeger.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "zhang li/Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "13910568360/15001135685";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com/mingxuan.xu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Transmitter";
item.properties["acmedl:VL_Company"] = "Endress + Hauser Shanghai Automation Equipment Co., Ltd. 上海恩德斯豪斯自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Yang";
item.properties["acmedl:VL_Telephone"] = "010-59572922";
item.properties["acmedl:VL_MobilePhone"] = "13501390765";
item.properties["acmedl:VL_Email"] = "Yang.chen@cn.endress.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Temperature Gauge";
item.properties["acmedl:VL_Company"] = "Beijing Brighty 北京布莱迪工程技术有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhang Qi";
item.properties["acmedl:VL_Telephone"] = "010-6763 3539";
item.properties["acmedl:VL_MobilePhone"] = "13601100782";
item.properties["acmedl:VL_Email"] = "zq@bj-brighty.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Differencial Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "zhang li/Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "13910568360/15001135685";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com/mingxuan.xu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "zhang li/Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "13910568360/15001135685";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com/mingxuan.xu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Transmitter";
item.properties["acmedl:VL_Company"] = "Endress + Hauser Shanghai Automation Equipment Co., Ltd. 上海恩德斯豪斯自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Yang";
item.properties["acmedl:VL_Telephone"] = "010-59572922";
item.properties["acmedl:VL_MobilePhone"] = "13501390765";
item.properties["acmedl:VL_Email"] = "Yang.chen@cn.endress.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Regulator";
item.properties["acmedl:VL_Company"] = "Cashco Inc. Shanghai Representative Office 美国Cashco有限公司上海代表处";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wang haoping";
item.properties["acmedl:VL_Telephone"] = "021-33927666";
item.properties["acmedl:VL_MobilePhone"] = "13910690743";
item.properties["acmedl:VL_Email"] = "mailto:millerw@gcpowertech.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Regulator";
item.properties["acmedl:VL_Company"] = "SAMSON Controls (China) Co., Ltd. 萨姆森控制（中国）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lu Yichun";
item.properties["acmedl:VL_Telephone"] = "021-54591580";
item.properties["acmedl:VL_MobilePhone"] = "18616878792";
item.properties["acmedl:VL_Email"] = "norbert@samsonchina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Regulator";
item.properties["acmedl:VL_Company"] = "Richards IndustriesValve Group-Jordan 美国理查德工业阀门集团-Jordan";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Yujun";
item.properties["acmedl:VL_Telephone"] = "021-62491718";
item.properties["acmedl:VL_MobilePhone"] = "13910534867";
item.properties["acmedl:VL_Email"] = "mailto:aiweiliu@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Pressure Regulator";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. -Fisher 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "talis.man";
item.properties["acmedl:VL_Telephone"] = "010-58211106";
item.properties["acmedl:VL_MobilePhone"] = "13816866104";
item.properties["acmedl:VL_Email"] = "mailto:talis.man@starcontrols.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Transmiter";
item.properties["acmedl:VL_Company"] = "VEGA";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Qi Bin";
item.properties["acmedl:VL_Telephone"] = "022-26273296";
item.properties["acmedl:VL_MobilePhone"] = "13821829370";
item.properties["acmedl:VL_Email"] = "mailto:qibin@vega.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Transmiter";
item.properties["acmedl:VL_Company"] = "Krohne measurement instrument(Shanghai) Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Jianzheng";
item.properties["acmedl:VL_Telephone"] = "021-64705656";
item.properties["acmedl:VL_MobilePhone"] = "13916323851";
item.properties["acmedl:VL_Email"] = "jeff.shen@krohne-asia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Transmiter";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "zhang li/Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "13910568360/15001135685";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com/mingxuan.xu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Transmiter";
item.properties["acmedl:VL_Company"] = "Endress + Hauser Shanghai Automation Equipment Co., Ltd. 上海恩德斯豪斯自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Yang";
item.properties["acmedl:VL_Telephone"] = "010-59572922";
item.properties["acmedl:VL_MobilePhone"] = "13501390765";
item.properties["acmedl:VL_Email"] = "Yang.chen@cn.endress.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Switch";
item.properties["acmedl:VL_Company"] = "Krohne measurement instrument(Shanghai) Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Shen Jianzheng";
item.properties["acmedl:VL_Telephone"] = "021-64705656";
item.properties["acmedl:VL_MobilePhone"] = "13916323851";
item.properties["acmedl:VL_Email"] = "jeff.shen@krohne-asia.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Switch";
item.properties["acmedl:VL_Company"] = "Emerson Process Management Co., Ltd. (Rosemount) 艾默生过程控制有限公司";
item.properties["acmedl:VL_Brand"] = "Emerson";
item.properties["acmedl:VL_Contact"] = "zhang li/Xu Mingxuan";
item.properties["acmedl:VL_Telephone"] = "010-5821 1221";
item.properties["acmedl:VL_MobilePhone"] = "13910568360/15001135685";
item.properties["acmedl:VL_Email"] = "Li.Zhang@emerson.com/mingxuan.xu@emerson.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Level Switch";
item.properties["acmedl:VL_Company"] = "Endress + Hauser Shanghai Automation Equipment Co., Ltd. 上海恩德斯豪斯自动化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Chen Yang";
item.properties["acmedl:VL_Telephone"] = "010-59572922";
item.properties["acmedl:VL_MobilePhone"] = "13501390765";
item.properties["acmedl:VL_Email"] = "Yang.chen@cn.endress.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Breath valve & Flame Arrestor";
item.properties["acmedl:VL_Company"] = "Baunschweiger Flammenfilter GmbH  (Brand: protego)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Wei";
item.properties["acmedl:VL_Telephone"] = "010-84885215";
item.properties["acmedl:VL_MobilePhone"] = "18910159257";
item.properties["acmedl:VL_Email"] = "protego_beijing@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Breath valve & Flame Arrestor";
item.properties["acmedl:VL_Company"] = "Tyco Flow Control (Beijing) Co,.Ltd. 泰科流体控制（北京）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yan Min";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "15900955892";
item.properties["acmedl:VL_Email"] = "ranyan@tyco-valves.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Breath valve & Flame Arrestor";
item.properties["acmedl:VL_Company"] = "Safety Systems UK Ltd. Beijing Rep. Office 英国安全系统有限公司北京代表处";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Xuejun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13910030499";
item.properties["acmedl:VL_Email"] = "xili@safetysystemsuk.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "On-off Valve";
item.properties["acmedl:VL_Company"] = "Flowserve Flow Control 福斯流体控制";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Andy Wu/Lola Zheng";
item.properties["acmedl:VL_Telephone"] = "0512-62881786";
item.properties["acmedl:VL_MobilePhone"] = "13913161158/15000586597";
item.properties["acmedl:VL_Email"] = "mailto:anwu@flowserve.com/Lzheng@flowserve.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "On-off Valve";
item.properties["acmedl:VL_Company"] = "SAMSON Controls (China) Co., Ltd. 萨姆森控制（中国）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lu Yichun";
item.properties["acmedl:VL_Telephone"] = "021-54591580";
item.properties["acmedl:VL_MobilePhone"] = "18616878792";
item.properties["acmedl:VL_Email"] = "mailto:norbert@samsonchina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VRV Air Conditioner";
item.properties["acmedl:VL_Company"] = "Mitsubishi三菱空调　";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Fu BinBin";
item.properties["acmedl:VL_Telephone"] = "021--31358990";
item.properties["acmedl:VL_MobilePhone"] = "13501644595";
item.properties["acmedl:VL_Email"] = "mailto:13501644595@vip.163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VRV Air Conditioner";
item.properties["acmedl:VL_Company"] = "Hitach　日立空调";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhong Xiaoming";
item.properties["acmedl:VL_Telephone"] = "021-63581603";
item.properties["acmedl:VL_MobilePhone"] = "13601759185";
item.properties["acmedl:VL_Email"] = "mailto:Michael.zhong@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "VRV Air Conditioner";
item.properties["acmedl:VL_Company"] = "Daikin 大金空调";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhu Dingyong";
item.properties["acmedl:VL_Telephone"] = "021-68221819";
item.properties["acmedl:VL_MobilePhone"] = "13918042345";
item.properties["acmedl:VL_Email"] = "mailto:zhu13918042345@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "HVAC";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Blower";
item.properties["acmedl:VL_Company"] = "上海诺地乐通用设备制造有限公司 (Infinair 英飞风机)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ji Guobing";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13914710058";
item.properties["acmedl:VL_Email"] = "mailto:13914710058@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Blower";
item.properties["acmedl:VL_Company"] = "Shanghai Blower Works Co.,Ltd. 上海鼓风机厂有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Lv Chunjin";
item.properties["acmedl:VL_Telephone"] = "021-56650577-398";
item.properties["acmedl:VL_MobilePhone"] = "13701992528";
item.properties["acmedl:VL_Email"] = "sales@sbw-cn.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Blower";
item.properties["acmedl:VL_Company"] = "HALIFAX 哈利法克斯风机（深圳）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Kevin Liang";
item.properties["acmedl:VL_Telephone"] = "0755-81490059-823";
item.properties["acmedl:VL_MobilePhone"] = "136-3255-2079";
item.properties["acmedl:VL_Email"] = "mailto:KevinLiang@halifax-fan.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Blower";
item.properties["acmedl:VL_Company"] = "Zhejiang Zhefeng group 浙江浙风集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr.Liang/ Ms.Xu";
item.properties["acmedl:VL_Telephone"] = "0575 82366508";
item.properties["acmedl:VL_MobilePhone"] = "13906850987/15258509430";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Blower";
item.properties["acmedl:VL_Company"] = "GREENHECK 格林瀚克通风设备（昆山）有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Yu Naizheng/ Zhang Jun(Ag)";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13761355913/15900782223";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Ventilation Fan";
item.properties["acmedl:VL_Company"] = "上海诺地乐通用设备制造有限公司 (Infinair 英飞风机)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Ji Guobing";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13914710058";
item.properties["acmedl:VL_Email"] = "mailto:13914710058@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();



