// Get/Create data list container
// var site = companyhome.childByNamePath("Sites/swsdp");
// var dataListContainer = "dataLists";
// var dataLists = site.getContainer(dataListContainer);
// var site = siteService.getSite("swsdp");
var site = siteService.getSite("vendor-list");
var dataLists = site.getContainer("dataLists");

var vendorListName = "Vendor List";
var vendorList = dataLists.childByNamePath(vendorListName);

var vendorListItemType = "acmedl:VendorListItem";

// Add an item to the vendor list

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Alfa Laval (China) Ltd.-Beijing Office";
item.properties["acmedl:VL_Brand"] = "Alfa Laval ";
item.properties["acmedl:VL_Contact"] = "Henry Lu";
item.properties["acmedl:VL_Telephone"] = "021-23225704";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "Henry.lu@alfalaval.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "VRV S.p.A";
item.properties["acmedl:VL_Brand"] = "VRV";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "+39 039 6025.1";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "info@vrv.com";
item.properties["acmedl:VL_Country"] = "Italy";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "";
item.properties["acmedl:VL_Company"] = "Chart Ferox";
item.properties["acmedl:VL_Brand"] = "Chart Ferox";
item.properties["acmedl:VL_Contact"] = "Czech Republic";
item.properties["acmedl:VL_Telephone"] = "+971 504 812 086";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "abdalla.abdalla@chart-ind.com";
item.properties["acmedl:VL_Country"] = "Czech Republic";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Cryovat Internationaal B.V.";
item.properties["acmedl:VL_Brand"] = "Cryovat";
item.properties["acmedl:VL_Contact"] = "Rien van Berkum";
item.properties["acmedl:VL_Telephone"] = "+31 (0) 33-245 59 59";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "e.h@tankbouwrootselaar.com";
item.properties["acmedl:VL_Country"] = "The Netherlands";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Linde AG";
item.properties["acmedl:VL_Brand"] = "Linde";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "+49.89.35757-01";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "CLNG.PROCUREMENT@LINDE-LE.COM";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "PACT Environment Technology Co., Ltd";
item.properties["acmedl:VL_Brand"] = "PACT";
item.properties["acmedl:VL_Contact"] = "Lucia Lu";
item.properties["acmedl:VL_Telephone"] = "021-53019081-242";
item.properties["acmedl:VL_MobilePhone"] = "13482124455";
item.properties["acmedl:VL_Email"] = "lulan@pactusa.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Cuno Filtration (Shanghai) Co., Ltd CUNO过滤设备（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "Cuno";
item.properties["acmedl:VL_Contact"] = "Echo Liao";
item.properties["acmedl:VL_Telephone"] = "010-65613336 ext.2128";
item.properties["acmedl:VL_MobilePhone"] = "13910209828";
item.properties["acmedl:VL_Email"] = "Eliao2@mmm.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Mahle";
item.properties["acmedl:VL_Brand"] = "Mahle";
item.properties["acmedl:VL_Contact"] = "Jason Huang";
item.properties["acmedl:VL_Telephone"] = "8621 51360618";
item.properties["acmedl:VL_MobilePhone"] = "13813811558";
item.properties["acmedl:VL_Email"] = "jason.huang@cn.mahle.com";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Whessoe";
item.properties["acmedl:VL_Brand"] = "Whessoe";
item.properties["acmedl:VL_Contact"] = "Martin Grewer";
item.properties["acmedl:VL_Telephone"] = "+44 (0)1325 390031";
item.properties["acmedl:VL_MobilePhone"] = "+44 (0)1325 390031";
item.properties["acmedl:VL_Email"] = "Martin.Grewer@whessoe.co.uk";
item.properties["acmedl:VL_Country"] = "UK";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Zhongyi FRP Group Co. Ltd.冀州中意复合材料有限公司";
item.properties["acmedl:VL_Brand"] = "Zhongyi";
item.properties["acmedl:VL_Contact"] = "Niu Zuohui";
item.properties["acmedl:VL_Telephone"] = "311-83826135";
item.properties["acmedl:VL_MobilePhone"] = "13931134390";
item.properties["acmedl:VL_Email"] = "davidniu775@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Shanghai Kingsun FRP Co., Ltd上海精雄钢铁制品有限公司";
item.properties["acmedl:VL_Brand"] = "Shanghai Kingsun";
item.properties["acmedl:VL_Contact"] = "Gao Jun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13811471852";
item.properties["acmedl:VL_Email"] = "kingsunbj@vip.sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Shandong Jinguang Fibreglass Group Co. Ltd.山东金光玻璃钢集团有限公司";
item.properties["acmedl:VL_Brand"] = "Shandong Jinguang";
item.properties["acmedl:VL_Contact"] = "Shandong Jinguang";
item.properties["acmedl:VL_Telephone"] = "0534-6366159";
item.properties["acmedl:VL_MobilePhone"] = "13001763771";
item.properties["acmedl:VL_Email"] = "dz_huang@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "China Dezhou Yatai Group德州亚太集团";
item.properties["acmedl:VL_Brand"] = "Dezhou Yatai ";
item.properties["acmedl:VL_Contact"] = "Li Hua";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13901016653";
item.properties["acmedl:VL_Email"] = "yatai_li@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Hangzhou Ying Da Vessel Engineering Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "Hangzhou Yingda";
item.properties["acmedl:VL_Contact"] = "Wen Jianfang";
item.properties["acmedl:VL_Telephone"] = "0571-86190728";
item.properties["acmedl:VL_MobilePhone"] = "13805713517";
item.properties["acmedl:VL_Email"] = "ydvc@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "PetroChina No.1 Chemical Equipment";
item.properties["acmedl:VL_Brand"] = "PetroChina";
item.properties["acmedl:VL_Contact"] = "Chen Liang";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13937999019";
item.properties["acmedl:VL_Email"] = "shebeichang001@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "PARESA S.p.A.";
item.properties["acmedl:VL_Brand"] = "PARESA";
item.properties["acmedl:VL_Contact"] = "PARESA S.p.A.";
item.properties["acmedl:VL_Telephone"] = "+39 0547 609417";
item.properties["acmedl:VL_MobilePhone"] = "+39 335 316416";
item.properties["acmedl:VL_Email"] = "ESozzi@paresa.it";
item.properties["acmedl:VL_Country"] = "Italy";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Sichuan Chuankong HE Co., Ltd";
item.properties["acmedl:VL_Brand"] = "Chuankong";
item.properties["acmedl:VL_Contact"] = "Zou Kaihong";
item.properties["acmedl:VL_Telephone"] = "0832-3206238";
item.properties["acmedl:VL_MobilePhone"] = "13982929480";
item.properties["acmedl:VL_Email"] = "sczkh0073@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "DooSan Mecatec Co. Ltd";
item.properties["acmedl:VL_Brand"] = "DooSan";
item.properties["acmedl:VL_Contact"] = "S.W.Sean Choi";
item.properties["acmedl:VL_Telephone"] = "82-55-270-0499";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "clclo@doosan.com";
item.properties["acmedl:VL_Country"] = "Korea";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "SUNPOWER GROUP LTD";
item.properties["acmedl:VL_Brand"] = "SUNPOWER";
item.properties["acmedl:VL_Contact"] = "Li Mingde";
item.properties["acmedl:VL_Telephone"] = "025-52169777";
item.properties["acmedl:VL_MobilePhone"] = "13581922792";
item.properties["acmedl:VL_Email"] = "Limd88@hotmail.com";
item.properties["acmedl:VL_Country"] = "Singapore";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Bellelli Engineering SpA";
item.properties["acmedl:VL_Brand"] = "Bellelli";
item.properties["acmedl:VL_Contact"] = "Riccardo Ravarotto";
item.properties["acmedl:VL_Telephone"] = "39 0425 595074";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "rravarotto@bellellieng.com";
item.properties["acmedl:VL_Country"] = "Italy";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "WUXI BAOFENG PETROCHEMICAL EQUIPMENT CO., LTD无锡宝丰石化装备有限公司";
item.properties["acmedl:VL_Brand"] = "Baofeng";
item.properties["acmedl:VL_Contact"] = "Mr. Guang Chen";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13675125749";
item.properties["acmedl:VL_Email"] = "guangchen78@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "Liyang Yunlong Chemical Equipment Group Co.溧阳市云龙化工设备集团有限公司";
item.properties["acmedl:VL_Brand"] = "Liyang Yunlong";
item.properties["acmedl:VL_Contact"] = "Zhu Yaping";
item.properties["acmedl:VL_Telephone"] = "0519-87368181/87228156";
item.properties["acmedl:VL_MobilePhone"] = "13915880058/13901496864";
item.properties["acmedl:VL_Email"] = "zyp@clyyl.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "KNM Special Process Equipment(Changshu)Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "KNM";
item.properties["acmedl:VL_Contact"] = "Karen Jiang";
item.properties["acmedl:VL_Telephone"] = "0512-5229 1869";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "karen@knm-changshu.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Haripin Exchanger";
item.properties["acmedl:VL_Company"] = "Lanpec technologies Limited甘肃蓝科石化高新装备股份有限公司 ";
item.properties["acmedl:VL_Brand"] = "Lanpec";
item.properties["acmedl:VL_Contact"] = "Wen Xiaolong";
item.properties["acmedl:VL_Telephone"] = "86-0931-7639685";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "wenxl_6911@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air-Cooled Heat Exchanger";
item.properties["acmedl:VL_Company"] = "HANGCHOU HANGYANG CO.,LTD.杭州杭氧股份有限公司";
item.properties["acmedl:VL_Brand"] = "Hangyang";
item.properties["acmedl:VL_Contact"] = "Mr.Feng";
item.properties["acmedl:VL_Telephone"] = "0571-85869185";
item.properties["acmedl:VL_MobilePhone"] = "18968153953";
item.properties["acmedl:VL_Email"] = "xuyi16@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air-Cooled Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Jord International Pty Ltd";
item.properties["acmedl:VL_Brand"] = "Jord";
item.properties["acmedl:VL_Contact"] = "steven Zhang";
item.properties["acmedl:VL_Telephone"] = "010 6444 0186";
item.properties["acmedl:VL_MobilePhone"] = "13910885731";
item.properties["acmedl:VL_Email"] = "szhang@jord.com.au";
item.properties["acmedl:VL_Country"] = "Australia";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air-Cooled Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Dalian bingshan";
item.properties["acmedl:VL_Brand"] = "Bingshan";
item.properties["acmedl:VL_Contact"] = "li zhishi";
item.properties["acmedl:VL_Telephone"] = "010-64333693";
item.properties["acmedl:VL_MobilePhone"] = "13910654220";
item.properties["acmedl:VL_Email"] = "li_zhishi@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air-Cooled Heat Exchanger";
item.properties["acmedl:VL_Company"] = "Sichuan Chuankong HE Co., Ltd四川川空换热器有限公司 ";
item.properties["acmedl:VL_Brand"] = "Chuankong";
item.properties["acmedl:VL_Contact"] = "Zhou Kaihong";
item.properties["acmedl:VL_Telephone"] = "0832-3206238";
item.properties["acmedl:VL_MobilePhone"] = "13982929480";
item.properties["acmedl:VL_Email"] = "sczkh0073@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air-Cooled Heat Exchanger";
item.properties["acmedl:VL_Company"] = "GEA Batignolles Thermal Technologies (Changshu) Co., Ltd.";
item.properties["acmedl:VL_Brand"] = "GEA";
item.properties["acmedl:VL_Contact"] = "Zhao Xin";
item.properties["acmedl:VL_Telephone"] = "21 6390-0959 Ext. 122";
item.properties["acmedl:VL_MobilePhone"] = "138 1724-5978";
item.properties["acmedl:VL_Email"] = "xin.zhao@geagroup.com";
item.properties["acmedl:VL_Country"] = "Germany";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Magetic Centrifugal Pump";
item.properties["acmedl:VL_Company"] = "Ebara Great Pump Co., Ltd. 嘉利特荏原";
item.properties["acmedl:VL_Brand"] = "Ebara";
item.properties["acmedl:VL_Contact"] = "Sun Yangguang 孙阳光";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13810590953";
item.properties["acmedl:VL_Email"] = "bj@ebaragreat.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "PSV";
item.properties["acmedl:VL_Company"] = "Beijing Aerospace Petrochemical Technology and Equipment Corporation 北京航天石化技术装备工程公司 (BSPC)";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Zhai Hongbo 翟洪波";
item.properties["acmedl:VL_Telephone"] = "010-52279636";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "zhaihb@calt1.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Compressor";
item.properties["acmedl:VL_Company"] = "百士吉泵业（上海）有限公司";
item.properties["acmedl:VL_Brand"] = "Blackmer";
item.properties["acmedl:VL_Contact"] = "Ricky Li";
item.properties["acmedl:VL_Telephone"] = "021-60722600";
item.properties["acmedl:VL_MobilePhone"] = "13701889114";
item.properties["acmedl:VL_Email"] = "ricky.li@psgchina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Compressor";
item.properties["acmedl:VL_Company"] = "Shanghai CAL-MECH Company Ltd.上海加洲机械有限公司";
item.properties["acmedl:VL_Brand"] = "Blackmer";
item.properties["acmedl:VL_Contact"] = "Wang Zhen 王震";
item.properties["acmedl:VL_Telephone"] = "021-31271585";
item.properties["acmedl:VL_MobilePhone"] = "13917552945";
item.properties["acmedl:VL_Email"] = "marlinwang@cal-mech.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Compressor";
item.properties["acmedl:VL_Company"] = "Beijing Stone Hi-Tech Co., Ltd 北京世通海泰科技发展有限公司";
item.properties["acmedl:VL_Brand"] = "Blackmer";
item.properties["acmedl:VL_Contact"] = "Cui Qiu 崔秋";
item.properties["acmedl:VL_Telephone"] = "021-5171-9336";
item.properties["acmedl:VL_MobilePhone"] = "13816293160";
item.properties["acmedl:VL_Email"] = "6181432@qq.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Seal Pump";
item.properties["acmedl:VL_Company"] = "大连帝国屏蔽电泵有限公司";
item.properties["acmedl:VL_Brand"] = "www.teikoku-china.com";
item.properties["acmedl:VL_Contact"] = "杨志刚";
item.properties["acmedl:VL_Telephone"] = "010-67664640";
item.properties["acmedl:VL_MobilePhone"] = "18970221817";
item.properties["acmedl:VL_Email"] = "dldgbj@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Non-Seal Pump 屏蔽泵";
item.properties["acmedl:VL_Company"] = "Dalian Hermetic Pump Co., Ltd. 大连海密梯克泵业有限公司";
item.properties["acmedl:VL_Brand"] = "Hermetic";
item.properties["acmedl:VL_Contact"] = "康建军 销售代表";
item.properties["acmedl:VL_Telephone"] = "0411-87581170";
item.properties["acmedl:VL_MobilePhone"] = "13644270786";
item.properties["acmedl:VL_Email"] = "kangjianjun@hermetic.com.cn";
item.properties["acmedl:VL_Country"] = "Dalian, P.R.China/ 北京办事处";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Motor";
item.properties["acmedl:VL_Company"] = "佳木斯电机股份有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "0454-8322120 0454-8322961";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Motor";
item.properties["acmedl:VL_Company"] = "WesTrac China Power Systems Dept. 柴油发电机组–威斯特动力系统部";
item.properties["acmedl:VL_Brand"] = "Caterpillar";
item.properties["acmedl:VL_Contact"] = "Gao Yuantun 高元屯";
item.properties["acmedl:VL_Telephone"] = "(86-10) 5902 1666 转 6001 ";
item.properties["acmedl:VL_MobilePhone"] = "18910856206";
item.properties["acmedl:VL_Email"] = "yuantun.gao@westrac.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Motor";
item.properties["acmedl:VL_Company"] = "ABB Electrical Machines Ltd";
item.properties["acmedl:VL_Brand"] = "ABB";
item.properties["acmedl:VL_Contact"] = "姜柳柳 Sales Engineer";
item.properties["acmedl:VL_Telephone"] = "021-23287941";
item.properties["acmedl:VL_MobilePhone"] = "13817183077";
item.properties["acmedl:VL_Email"] = "Liuliu.jiang@cn.abb.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "S&T Heat Exchanger;#Air Cooler";
item.properties["acmedl:VL_Company"] = "THT Heat Transfer Technology, Inc. 巨元企业";
item.properties["acmedl:VL_Brand"] = "THT";
item.properties["acmedl:VL_Contact"] = "Yue Bin";
item.properties["acmedl:VL_Telephone"] = "0434-3265325  3262871";
item.properties["acmedl:VL_MobilePhone"] = "13258791100";
item.properties["acmedl:VL_Email"] = "yuebin@tht.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Valve - Ball;#Solenoid Valve";
item.properties["acmedl:VL_Company"] = "塞日（上海）机械设备有限公司";
item.properties["acmedl:VL_Brand"] = "Meca-inox低温深冷球阀/ASCO 电磁阀/Festo电磁阀阀岛";
item.properties["acmedl:VL_Contact"] = "胡习专 Hero Hu";
item.properties["acmedl:VL_Telephone"] = "021-54065700-282";
item.properties["acmedl:VL_MobilePhone"] = "13817193052";
item.properties["acmedl:VL_Email"] = "hero.hu@itechchina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Vessel and Seperator";
item.properties["acmedl:VL_Company"] = "博思特能源装备天津股份有限公司";
item.properties["acmedl:VL_Brand"] = "博思特";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "022-22193891";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Vessel & Heat Exchanger";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "FGC compressor";
item.properties["acmedl:VL_Company"] = "沈阳远大压缩机股份有限公司（YDCC）";
item.properties["acmedl:VL_Brand"] = "yuanda";
item.properties["acmedl:VL_Contact"] = "霍维斌";
item.properties["acmedl:VL_Telephone"] = "024 -25369782";
item.properties["acmedl:VL_MobilePhone"] = "13840190527";
item.properties["acmedl:VL_Email"] = "13840190527@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "FGC compressor";
item.properties["acmedl:VL_Company"] = "山东科瑞集团国内销售中心-北京分公司";
item.properties["acmedl:VL_Brand"] = "kerui";
item.properties["acmedl:VL_Contact"] = "栾宗瑾";
item.properties["acmedl:VL_Telephone"] = "+86 10 84775059";
item.properties["acmedl:VL_MobilePhone"] = "134 6676 9028";
item.properties["acmedl:VL_Email"] = "luanzj@keruigroup.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Liquid Drain Traps疏水阀";
item.properties["acmedl:VL_Company"] = "斯派莎克Spiraxsarco";
item.properties["acmedl:VL_Brand"] = "斯派莎克";
item.properties["acmedl:VL_Contact"] = "Liu Feng";
item.properties["acmedl:VL_Telephone"] = "86 25 84610937";
item.properties["acmedl:VL_MobilePhone"] = "15062282178";
item.properties["acmedl:VL_Email"] = "mailto:liufeng@cn.spiraxsarco.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Liquid Drain Traps疏水阀";
item.properties["acmedl:VL_Company"] = "Armstrong International";
item.properties["acmedl:VL_Brand"] = "Armstrong";
item.properties["acmedl:VL_Contact"] = "Mr Song";
item.properties["acmedl:VL_Telephone"] = "010-59063003";
item.properties["acmedl:VL_MobilePhone"] = "13811916362";
item.properties["acmedl:VL_Email"] = "mailto:songmy@armstrong.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Silencer";
item.properties["acmedl:VL_Company"] = "上海实华集团";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "周  亮";
item.properties["acmedl:VL_Telephone"] = "021-51085858-8888";
item.properties["acmedl:VL_MobilePhone"] = "13916303468";
item.properties["acmedl:VL_Email"] = "mailto:shihua@shjx.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Silencer";
item.properties["acmedl:VL_Company"] = "湖北洪湖荣昌石化设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "谢均祥";
item.properties["acmedl:VL_Telephone"] = "0716-2852712";
item.properties["acmedl:VL_MobilePhone"] = "13886630386";
item.properties["acmedl:VL_Email"] = "mailto:rongchangshihua@vip.163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Silencer";
item.properties["acmedl:VL_Company"] = "启动市科威石化机械设备有限公司";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mr Shi";
item.properties["acmedl:VL_Telephone"] = "0513-83628188";
item.properties["acmedl:VL_MobilePhone"] = "13906283886";
item.properties["acmedl:VL_Email"] = "mailto:webmaster@ke-wei.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Demister pad";
item.properties["acmedl:VL_Company"] = "ACS";
item.properties["acmedl:VL_Brand"] = "ACS";
item.properties["acmedl:VL_Contact"] = "Hu";
item.properties["acmedl:VL_Telephone"] = "021-5048 1338";
item.properties["acmedl:VL_MobilePhone"] = "13916702400";
item.properties["acmedl:VL_Email"] = "mailto:whu@acsind.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Demister pad";
item.properties["acmedl:VL_Company"] = "Sulzer Shanghai";
item.properties["acmedl:VL_Brand"] = "Sulzer";
item.properties["acmedl:VL_Contact"] = "Nemo Ren (任琦)";
item.properties["acmedl:VL_Telephone"] = "86 (21) 60365136";
item.properties["acmedl:VL_MobilePhone"] = "18628083700";
item.properties["acmedl:VL_Email"] = "mailto:Qi.Ren@sulzer.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "FGC compressor";
item.properties["acmedl:VL_Company"] = "沈阳透平机械股份有限公司往复机事业部";
item.properties["acmedl:VL_Brand"] = "shengu";
item.properties["acmedl:VL_Contact"] = "余波";
item.properties["acmedl:VL_Telephone"] = "024-25801099";
item.properties["acmedl:VL_MobilePhone"] = "13998853894";
item.properties["acmedl:VL_Email"] = "yjn1999@sina.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Spring Hanger";
item.properties["acmedl:VL_Company"] = "Bergen Pipe Supports (Jiangsu) Limited";
item.properties["acmedl:VL_Brand"] = "Bergen";
item.properties["acmedl:VL_Contact"] = "Joyce Jiao";
item.properties["acmedl:VL_Telephone"] = "0523 8462 1530";
item.properties["acmedl:VL_MobilePhone"] = "(0)158 6107 7660";
item.properties["acmedl:VL_Email"] = "mailto:joyce.jiao@pipesupports.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Spring Hanger";
item.properties["acmedl:VL_Company"] = "Nanjing Sunpower(中圣)";
item.properties["acmedl:VL_Brand"] = "Sunpower(中圣)";
item.properties["acmedl:VL_Contact"] = "李宋光";
item.properties["acmedl:VL_Telephone"] = "025-51198007";
item.properties["acmedl:VL_MobilePhone"] = "13915950892";
item.properties["acmedl:VL_Email"] = "mailto:sgli@sunpower.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Spring Hanger";
item.properties["acmedl:VL_Company"] = "Lisega Pipe Support";
item.properties["acmedl:VL_Brand"] = "Lisega";
item.properties["acmedl:VL_Contact"] = "Yuan Yang";
item.properties["acmedl:VL_Telephone"] = "010-63951205";
item.properties["acmedl:VL_MobilePhone"] = "13601385177";
item.properties["acmedl:VL_Email"] = "mailto:yang.yuan@cn.lisega.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fabricator";
item.properties["acmedl:VL_Company"] = "Libote";
item.properties["acmedl:VL_Brand"] = "Libote";
item.properties["acmedl:VL_Contact"] = "Cai Zhigang";
item.properties["acmedl:VL_Telephone"] = "0512-82032323";
item.properties["acmedl:VL_MobilePhone"] = "13701863743";
item.properties["acmedl:VL_Email"] = "caizhigang@n23china.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fabricator";
item.properties["acmedl:VL_Company"] = "Furui";
item.properties["acmedl:VL_Brand"] = "Furui";
item.properties["acmedl:VL_Contact"] = "Norman Wu";
item.properties["acmedl:VL_Telephone"] = "021-33634315-608";
item.properties["acmedl:VL_MobilePhone"] = "189 168 88838";
item.properties["acmedl:VL_Email"] = "whq@furuise.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Architecture";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Fabricator";
item.properties["acmedl:VL_Company"] = "Shanghai YanDa Engineering Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "Yanda";
item.properties["acmedl:VL_Contact"] = "Lv Ling";
item.properties["acmedl:VL_Telephone"] = "021-57448229";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "business@yanda.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Architecture";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "loading arm";
item.properties["acmedl:VL_Company"] = "JiangSu Changlong Technologies Co., Ltd";
item.properties["acmedl:VL_Brand"] = "changlong";
item.properties["acmedl:VL_Contact"] = "Tommy Zhou";
item.properties["acmedl:VL_Telephone"] = "0512 5817 2711";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "tommy@ccltech.com.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "valve";
item.properties["acmedl:VL_Company"] = "超达阀门集团股份有限公司";
item.properties["acmedl:VL_Brand"] = "Chaoda";
item.properties["acmedl:VL_Contact"] = "梁艺骏";
item.properties["acmedl:VL_Telephone"] = "0577-67319939  010-6497 6072";
item.properties["acmedl:VL_MobilePhone"] = "139 0411 8969";
item.properties["acmedl:VL_Email"] = "liangyijun0411@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "valve";
item.properties["acmedl:VL_Company"] = "埃克美迅(意大利)管路控制系统上海代表处";
item.properties["acmedl:VL_Brand"] = "Italy Eicmation control vlv";
item.properties["acmedl:VL_Contact"] = "杨永胜";
item.properties["acmedl:VL_Telephone"] = "086-21-63808573";
item.properties["acmedl:VL_MobilePhone"] = "15606223795";
item.properties["acmedl:VL_Email"] = "yang20120718@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Instrument";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "valve";
item.properties["acmedl:VL_Company"] = "广东华南特种气体研究所有限公司";
item.properties["acmedl:VL_Brand"] = "英国Bestobell低温阀";
item.properties["acmedl:VL_Contact"] = "彭芳";
item.properties["acmedl:VL_Telephone"] = "0757-8512 7232";
item.properties["acmedl:VL_MobilePhone"] = "139 2776 7587";
item.properties["acmedl:VL_Email"] = "jody20060201@126.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Piping";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Process compresser";
item.properties["acmedl:VL_Company"] = "Johnson Controls";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Mandy Ji";
item.properties["acmedl:VL_Telephone"] = "021-62766509*8413";
item.properties["acmedl:VL_MobilePhone"] = "13564389221";
item.properties["acmedl:VL_Email"] = "Minmin.Ji@jci.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Pall Filter (Beijing) Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Wang Lu";
item.properties["acmedl:VL_Telephone"] = "010-67802288";
item.properties["acmedl:VL_MobilePhone"] = "13981889376";
item.properties["acmedl:VL_Email"] = "mailto:lu_wang@ap.pall.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Filter";
item.properties["acmedl:VL_Company"] = "Feature (WuXi) Filtration Technology Co.,Ltd.";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "He Sheng";
item.properties["acmedl:VL_Telephone"] = "021 63847332";
item.properties["acmedl:VL_MobilePhone"] = "13901831076";
item.properties["acmedl:VL_Email"] = "samhesh@feature-tec.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Cooler";
item.properties["acmedl:VL_Company"] = "Harbin Air Conditioning Co., Ltd";
item.properties["acmedl:VL_Brand"] = "HAC";
item.properties["acmedl:VL_Contact"] = "Lv Yayan";
item.properties["acmedl:VL_Telephone"] = "010-68002389";
item.properties["acmedl:VL_MobilePhone"] = "13717860835";
item.properties["acmedl:VL_Email"] = "lyy-lsn@163.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Cooler";
item.properties["acmedl:VL_Company"] = "Wuxi General Chemical Equipment Co.Ltd.";
item.properties["acmedl:VL_Brand"] = "WGC";
item.properties["acmedl:VL_Contact"] = "Cao Honghai";
item.properties["acmedl:VL_Telephone"] = "0510-5632888";
item.properties["acmedl:VL_MobilePhone"] = "13506187799";
item.properties["acmedl:VL_Email"] = "caoh@chemwgcep.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Air Cooler";
item.properties["acmedl:VL_Company"] = "Jord International";
item.properties["acmedl:VL_Brand"] = "JORD";
item.properties["acmedl:VL_Contact"] = "maxiang";
item.properties["acmedl:VL_Telephone"] = "010-6445 9331";
item.properties["acmedl:VL_MobilePhone"] = "13601328914";
item.properties["acmedl:VL_Email"] = "mailto:mma@jord.com.au";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Distribution Panel";
item.properties["acmedl:VL_Company"] = "Cooper Crouse-Hinds Tianjin";
item.properties["acmedl:VL_Brand"] = "COOPER";
item.properties["acmedl:VL_Contact"] = "Cindy Sun";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "151 2299 7855";
item.properties["acmedl:VL_Email"] = "cindy.sun@cooperindustries.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Distribution Panel";
item.properties["acmedl:VL_Company"] = "Schneider";
item.properties["acmedl:VL_Brand"] = "Schneider";
item.properties["acmedl:VL_Contact"] = "Cui Zhida";
item.properties["acmedl:VL_Telephone"] = "";
item.properties["acmedl:VL_MobilePhone"] = "13386161199";
item.properties["acmedl:VL_Email"] = "mailto:zhida.cui@cn.schneider-electric.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LV Transformer";
item.properties["acmedl:VL_Company"] = "Moeller";
item.properties["acmedl:VL_Brand"] = "Moeller";
item.properties["acmedl:VL_Contact"] = "Gao Yuliang";
item.properties["acmedl:VL_Telephone"] = "010-65906560";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "LV Transformer";
item.properties["acmedl:VL_Company"] = "Chint Electric Co., Ltd";
item.properties["acmedl:VL_Brand"] = "Chint";
item.properties["acmedl:VL_Contact"] = "Liu Diantao";
item.properties["acmedl:VL_Telephone"] = "021-67777777-80963";
item.properties["acmedl:VL_MobilePhone"] = "13917745617";
item.properties["acmedl:VL_Email"] = "liudt@chint.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Electrical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "Callidus Technologies L.L.C";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Li Pengyu";
item.properties["acmedl:VL_Telephone"] = "010-67081998";
item.properties["acmedl:VL_MobilePhone"] = "13501152359";
item.properties["acmedl:VL_Email"] = "jscbeijg@mx.cei.gov.cn";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "SAMIA BJ";
item.properties["acmedl:VL_Brand"] = "SAMIA";
item.properties["acmedl:VL_Contact"] = "Wilson Yan";
item.properties["acmedl:VL_Telephone"] = "010-65389618";
item.properties["acmedl:VL_MobilePhone"] = "13699137911";
item.properties["acmedl:VL_Email"] = "wilsonyan@samiabj.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Flare";
item.properties["acmedl:VL_Company"] = "Shanghai Marine Diesel Engine 711 Research Institute";
item.properties["acmedl:VL_Brand"] = "";
item.properties["acmedl:VL_Contact"] = "Liu Shijun";
item.properties["acmedl:VL_Telephone"] = "021-31310244";
item.properties["acmedl:VL_MobilePhone"] = "13801705687";
item.properties["acmedl:VL_Email"] = "mailto:LSJ711@126.COM";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Process";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Immersed pump";
item.properties["acmedl:VL_Company"] = "ACD";
item.properties["acmedl:VL_Brand"] = "ACD";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "41 61 413 0230";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:sales@acdcryo.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Immersed pump";
item.properties["acmedl:VL_Company"] = "Ebara";
item.properties["acmedl:VL_Brand"] = "Ebara";
item.properties["acmedl:VL_Contact"] = "Li Qingsong";
item.properties["acmedl:VL_Telephone"] = "010-65908150";
item.properties["acmedl:VL_MobilePhone"] = "13901120364";
item.properties["acmedl:VL_Email"] = "mailto:lqs@ebarabj.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Immersed pump";
item.properties["acmedl:VL_Company"] = "CRYOSTAR";
item.properties["acmedl:VL_Brand"] = "CRYOSTAR";
item.properties["acmedl:VL_Contact"] = "Choi,Eric";
item.properties["acmedl:VL_Telephone"] = "0571 8536 8331";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "Eric.Choi@cryostar.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Positive displacement pumps";
item.properties["acmedl:VL_Company"] = "BRAN+LUEBBE";
item.properties["acmedl:VL_Brand"] = "BRAN+LUEBBE";
item.properties["acmedl:VL_Contact"] = "Liu Hongbo";
item.properties["acmedl:VL_Telephone"] = "010-59267283";
item.properties["acmedl:VL_MobilePhone"] = "13803225878";
item.properties["acmedl:VL_Email"] = "mailto:hongbo.liu@spx.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Positive displacement pumps";
item.properties["acmedl:VL_Company"] = "Metpro";
item.properties["acmedl:VL_Brand"] = "Metpro";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "(215) 723-6751";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "mailto:mpr@met-pro.com";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();

var item = vendorList.createNode(null, vendorListItemType);
item.properties["acmedl:VL_Commodity"] = "Positive displacement pumps";
item.properties["acmedl:VL_Company"] = "Myers Aplex";
item.properties["acmedl:VL_Brand"] = "Myers Aplex";
item.properties["acmedl:VL_Contact"] = "";
item.properties["acmedl:VL_Telephone"] = "419-289-6898";
item.properties["acmedl:VL_MobilePhone"] = "";
item.properties["acmedl:VL_Email"] = "";
item.properties["acmedl:VL_Country"] = "";
item.properties["acmedl:VL_Descipline"] = "Mechanical";
item.save();


